/**
 * Hand-authored content for /guides and /guides/<slug>.
 *
 * Unlike spec-data.ts (generated from core/), there is no canonical source
 * for this content elsewhere in the monorepo: it lives here. Adding a new
 * guide is one new object appended to `guideEntries`; no new .vue file, no
 * manual route/sitemap/llms edit (all three are derived from this file, see
 * nuxt.config.ts, scripts/gen-sitemap.ts, scripts/gen-llms.ts).
 *
 * `text` fields may contain inline <code>/<strong>/<a>: rendered with
 * v-html in GuideBody.vue, same convention spec pages use for prose.
 */

export type GuideCategory = 'vs' | 'practice' | 'concepts'

export type GuideBlock =
  | { type: 'p'; text: string }
  | { type: 'h2'; text: string }
  | { type: 'list'; items: string[] }
  | { type: 'code'; lang: string; code: string; label?: string }
  | { type: 'callout'; tone: 'do' | 'dont'; text: string }
  | { type: 'table'; head: string[]; rows: string[][] }

export interface GuideFaq { q: string; a: string }

export interface GuideEntry {
  slug: string
  category: GuideCategory
  navLabel: string
  title: string
  dek: string
  seoTitle: string
  seoDescription: string
  datePublished: string
  dateModified: string
  body: GuideBlock[]
  faq: GuideFaq[]
  related: string[]
}

export const guideCategoryLabels: Record<GuideCategory, string> = {
  vs: 'Comparisons',
  practice: 'Best practices',
  concepts: 'Concepts'
}

export const guideEntries: GuideEntry[] = [
  // ── Comparisons ──────────────────────────────────────────────────────────
  {
    slug: 'vs-css',
    category: 'vs',
    navLabel: '.gui vs CSS',
    title: '.gui vs CSS: a file format vs a styling language',
 dek: 'CSS styles a document that already exists somewhere else. .gui is the document: structure, layout, and appearance in one file, with no cascade to fight.',
 seoTitle: '.gui vs CSS: what’s the difference? | .gui Guides',
 seoDescription: 'CSS is a styling language layered onto HTML’s DOM. .gui is a self-contained file format for the whole interface: no cascade, no specificity, no host document required.',
    datePublished: '2026-07-10',
    dateModified: '2026-07-10',
    body: [
 { type: 'p', text: '<strong>CSS styles something that already exists.</strong> It is a rule language that attaches presentation to a DOM another format (HTML) already built: selectors, specificity, inheritance, a cascade that resolves at render time based on document order and rule weight. <strong>.gui is the thing itself.</strong> A <code>.gui</code> file is a zip package (<code>design.guix</code> markup, an <code>assets/</code> folder, a <code>preview.webp</code> thumbnail) that fully describes one interface: structure, layout, and appearance, together, in one file. There is no separate document to style and no cascade to resolve, because there is nothing upstream of it.' },
      { type: 'h2', text: 'What that actually changes' },
      { type: 'p', text: 'In CSS, the same element can end up styled by five different rules from three different files, and the final appearance depends on specificity math and load order. Reading a stylesheet does not tell you what anything looks like: you have to run the cascade in your head. In <code>.gui</code>, every node carries its own resolved appearance attributes directly, plus optional <a href="/spec/tokens">design tokens</a> for values meant to repeat (<code>$brand</code>, <code>$spacing-md</code>): a flat, named-reference system rather than CSS custom properties, since a <code>--variable</code> implies a CSS runtime and <code>.gui</code> is platform-agnostic (<a href="https://github.com/dotgui/core/blob/main/rfcs/0005-token-system.md">RFC-0005</a>). There is one place a value lives and one place it’s read from.' },
      { type: 'p', text: 'Layout works the same way. CSS spacing between siblings is usually simulated: margins on the parent or child, sometimes an empty spacer element left over from table-layout habits. <code>.gui</code>’s <a href="/spec/row"><code>row</code></a>, <a href="/spec/col"><code>col</code></a>, and <a href="/spec/grid"><code>grid</code></a> elements take a literal <code>gap</code> attribute: one declared number, no simulated elements. See <a href="/guides/spacing-and-gaps">Spacing and gaps</a>.' },
      { type: 'h2', text: 'Direction and alignment as values, not axis algebra' },
 { type: 'p', text: 'CSS expresses "these children run horizontally, evenly spaced" as a style declaration repeated on every container (<code>display: flex; flex-direction: row; gap: 16px</code>) whether it’s hand-written or generated by a utility system like Tailwind’s class list. <code>.gui</code> expresses the same thing as one element: <code>&lt;row gap="16"&gt;</code>. Direction is the tag itself, not a property that has to be set correctly and can silently be left off: see <a href="https://github.com/dotgui/core/blob/main/rfcs/0006-layout-sugar-tags.md">RFC-0006</a>.' },
      { type: 'p', text: 'Alignment follows the same pattern. CSS splits it into two axis-relative properties (<code>justify-content</code> for the main axis, <code>align-items</code> for the cross axis) and which axis is "main" flips depending on <code>flex-direction</code>, a piece of mental bookkeeping baked into the model. <code>.gui</code> replaced both with a single <code>align</code> attribute using nine positional values (<code>top-left</code> … <code>bottom-right</code>) that always name a visual position directly, the way a designer already describes layout, rather than a main-axis/cross-axis calculation: modeled on Figma’s own alignment grid, not flexbox terminology (see <a href="https://github.com/dotgui/core/blob/main/rfcs/0012-align-9point.md">RFC-0012</a>).' },
      { type: 'p', text: 'There’s no controlled benchmark for the token difference this makes, but the intent is explicit in the format’s own design record: a single <code>row</code> or one <code>align="middle-center"</code> value is harder for a model to get wrong than a multi-property, axis-relative CSS block, and there’s less text to generate for the same layout intent either way.' },
      { type: 'h2', text: 'Why this matters for AI agents' },
      { type: 'p', text: 'An agent asked to "style this the way the mockup looks" using CSS has to reason about cascade order across every stylesheet that could touch the element. An agent asked to change a <code>.gui</code> node’s fill changes one attribute on one node: nothing else in the file is implicated. That’s also what makes <code>.gui</code> deterministically <a href="/spec/quality">scoreable</a>: a validator can check a CSS ruleset for syntax errors, but it can’t tell you the cascade produced a sane result. A <code>.gui</code> file’s resolved appearance is just sitting there, readable, checkable.' },
 { type: 'p', text: '<strong>.gui</strong> is not trying to replace CSS on the web: a browser still needs CSS to paint DOM. What <code>.gui</code> replaces is using CSS (or a CSS-in-JS system, or Tailwind classes) as the source of truth for a design. The design lives in the <code>.gui</code> file; CSS, if it appears at all, is one possible render target for it, generated rather than hand-maintained.' }
    ],
    faq: [
 { q: 'Does .gui replace CSS?', a: 'No: a browser still uses CSS to paint. .gui replaces CSS (or any styling system) as the source of truth for a design: the design lives in the .gui file, and any styling code is a generated render target, not the original.' },
      { q: 'Why doesn’t .gui have a cascade?', a: 'Because every node carries its own resolved appearance directly, plus optional token references for values meant to repeat. There’s no upstream document to cascade from, so there’s nothing to resolve: what you read on a node is what renders.' },
 { q: 'How does .gui handle repeated values without a cascade?', a: 'Design tokens ($brand, $spacing-md, etc.): a node references a token by name instead of repeating a literal value. That gets you reuse without needing cascade or inheritance rules to find out which value actually applies.' }
    ],
    related: ['vs-html', 'spacing-and-gaps', 'ccac-score']
  },
  {
    slug: 'vs-html',
    category: 'vs',
    navLabel: '.gui vs HTML',
    title: '.gui vs HTML: a closed vocabulary vs an open runtime',
    dek: 'HTML is a programming surface that happens to describe UI. .gui is a static, closed vocabulary that always terminates in the same picture, everywhere.',
 seoTitle: '.gui vs HTML: how are they different? | .gui Guides',
 seoDescription: 'HTML plus CSS and JS is an open, scriptable runtime. .gui is a closed, static vocabulary of layout and shape elements with no logic: which is what makes it diffable and scoreable.',
    datePublished: '2026-07-10',
    dateModified: '2026-07-10',
    body: [
 { type: 'p', text: 'HTML, in practice, is never just HTML: it’s HTML plus CSS plus JavaScript, an open runtime where arbitrary code can mutate the DOM at any time. Two loads of the same page can render differently depending on network timing, a feature flag, or a script that hasn’t finished executing yet. <strong>.gui has no scripting.</strong> It is a closed, fixed vocabulary (<code>row</code>, <code>col</code>, <code>frame</code>, <code>grid</code>, <code>text</code>, <code>img</code>, <code>rect</code>, <code>ellipse</code>, <code>line</code>) and nothing in that vocabulary can execute logic. A given <code>.gui</code> file renders to the same picture every time, on every renderer, because there is no code path for it to do otherwise.' },
      { type: 'h2', text: 'What "closed vocabulary" buys you' },
      { type: 'p', text: 'A file that can’t run code is a file that can be fully understood by reading it. That’s what makes a <code>.gui</code> file <strong>diffable</strong> (two versions differ by exactly the attributes that changed, not by whatever a script does at runtime), <strong>validatable</strong> (a fixed vocabulary has a fixed set of legal shapes to check against), and <strong>scoreable</strong> (see <a href="/spec/quality">the CCAC model</a>): none of which is meaningfully possible for an arbitrary HTML+JS bundle, because the actual rendered result depends on execution, not just the source.' },
      { type: 'h2', text: 'Where HTML still wins' },
 { type: 'p', text: 'HTML is the right choice when the interface needs behavior: a live feed, client-side validation, a WebSocket connection. <code>.gui</code> is not a competitor there; it’s a source-of-truth format for the design that a real app (in HTML, SwiftUI, Jetpack Compose, whatever) then gets built from. The <a href="/embed"><code>&lt;gui-embed&gt;</code></a> library renders a <code>.gui</code> file directly on a web page with one script tag when you do want it live in a browser, but the file itself stays inert: no logic, no side effects, same output every render.' },
 { type: 'p', text: 'The role vocabulary closes the same gap semantic HTML tries to close with tags like <code>&lt;nav&gt;</code> or <code>&lt;article&gt;</code>: except <code>.gui</code>’s <a href="/spec/roles">53 roles</a> (<a href="https://github.com/dotgui/core/blob/main/rfcs/0041-role-attribute.md">RFC-0041</a>) are a closed, enumerated set rather than a loose convention, so <code>role="button"</code> means the same thing in every file, not "probably a button, check the click handler to be sure."' },
      { type: 'h2', text: 'Borrowing the idea, not the tax' },
 { type: 'p', text: 'HTML started as a simple trio: markup, style, script. In practice almost nobody hand-writes plain HTML for a real interface today; the actual authoring surface is a JavaScript framework (React, Vue, and the rest) sitting on top, and that layer is where most of the weight now lives. HTML won by adoption, not because raw markup is a great design representation: it’s the one format every browser, tool, and person already knows, so "design in code" defaults to it by network effect more than by merit.' },
 { type: 'p', text: 'The markup itself is a deliberate, direct descendant of that instinct: <code>.gui</code> is XML-inspired rather than JSON, specifically because a tag name carries meaning a JSON <code>"type"</code> key has to fake, and because every major model has been trained on enormous amounts of tag-based markup: asking an agent to write <code>.gui</code> is closer to asking it to write JSX than to invent a new schema (<a href="https://github.com/dotgui/core/blob/main/rfcs/0001-xml-over-json.md">RFC-0001</a>).' },
 { type: 'p', text: '<code>.gui</code> borrows HTML’s actual insight (plain markup any tool can parse, no proprietary format underneath) while trying not to inherit what widespread adoption did to it. A small, concrete example lives in its own layout vocabulary: the underlying primitive is a single <a href="/spec/stack"><code>&lt;stack direction="..."&gt;</code></a> element, but writing <code>direction="horizontal"</code> on every row-shaped container turned out to be noisy in practice, so <code>&lt;row&gt;</code>, <code>&lt;col&gt;</code>, and <code>&lt;grid&gt;</code> exist as sugar that drop the <code>direction</code> attribute for the common case (<a href="https://github.com/dotgui/core/blob/main/rfcs/0006-layout-sugar-tags.md">RFC-0006</a>). Same capability, less to write, less for an agent to get wrong: cutting tax on an idea, not just copying it.' }
    ],
    faq: [
      { q: 'Can a .gui file contain JavaScript or run logic?', a: 'No. The element vocabulary is closed and static: there is no scripting surface. A .gui file always renders to the same output because there is no code path for it to differ.' },
      { q: 'Is .gui meant to replace HTML for building apps?', a: 'No. HTML (or SwiftUI, Compose, etc.) is still the right choice for interfaces with real behavior. .gui is a source-of-truth design format those apps get built from, not a runtime.' },
 { q: 'How does .gui handle semantic meaning without HTML tags like <nav> or <button>?', a: 'A closed 53-role vocabulary via the role= attribute: role="button", role="nav-bar", and so on. Unlike semantic HTML, every role means exactly one thing everywhere, since the vocabulary is fixed rather than a loose convention.' },
 { q: 'Is row/col/grid a different format from stack, or the same thing?', a: 'The same thing. row, col, and grid are sugar tags for stack with a direction already set: row is stack direction="horizontal", col is stack direction="vertical". stack remains valid to write directly; the sugar tags just remove the extra attribute for the common case.' }
    ],
    related: ['vs-css', 'vs-svg', 'common-agent-mistakes']
  },
  {
    slug: 'vs-figma',
    category: 'vs',
    navLabel: '.gui vs Figma',
    title: '.gui vs Figma files: portable text vs a vendor’s app',
    dek: 'A Figma file only exists inside Figma. A .gui file is plain text in a zip: readable, diffable, and versionable without opening any design tool.',
 seoTitle: '.gui vs a Figma file: what changes? | .gui Guides',
    seoDescription: 'A Figma file lives inside Figma’s app and servers. A .gui file is a portable zip of plain-text XML: no vendor lock, git-diffable, and authorable without a design tool at all.',
    datePublished: '2026-07-10',
    dateModified: '2026-07-10',
    body: [
 { type: 'p', text: 'A Figma file is only fully readable inside Figma: the app, the API, or an export. It’s an excellent design environment, but the file itself is not a portable artifact you can open in a text editor, diff in git, or hand to an agent without going through Figma’s servers. <strong>A <code>.gui</code> file is plain text.</strong> Unzip it and <code>design.guix</code> is readable XML: open it in any editor, <code>git diff</code> it line by line, generate it from a script with no design tool involved at all.' },
      { type: 'h2', text: '.gui doesn’t require Figma' },
 { type: 'p', text: 'The <a href="/figma">Figma plugin</a> (coming soon (currently in review) will export any Figma layer tree to a <code>.gui</code> file) auto-layout, fills, gradients, effects, and tokens carried over as a 1:1 mapping of Figma’s own layer model, not approximated. That makes Figma <strong>one entry point among several</strong>, not a requirement. Today, an agent can already write a <code>.gui</code> file directly from a prompt with no design tool touched at any point: see <a href="/guides/prompting-your-agent">Prompting your agent</a>.' },
      { type: 'h2', text: 'The loop, not a one-way export' },
      { type: 'p', text: 'Because the same file is legible to both a design tool and an agent, it can move in either direction: an agent writes <code>home.gui</code>, a designer opens it in Figma to nudge a color, the file goes back to the agent to wire up. Every stop in that loop reads and writes the same file: nothing gets re-derived from a screenshot at each step. That loop is the actual point; Figma export is one leg of it, not the whole story.' },
      { type: 'h2', text: 'No live connection required' },
 { type: 'p', text: 'Figma’s own AI integration path runs through MCP (Model Context Protocol): a live tool-calling connection where an agent queries Figma’s API, often across several round-trips, to reconstruct a design piece by piece. Exporting to <code>.gui</code> once removes that dependency: the result is a static file an agent reads directly, with no persistent connection, no repeated API calls, and no dependency on Figma’s servers being reachable at generation time.' }
    ],
    faq: [
      { q: 'Do I need Figma to create a .gui file?', a: 'No. An AI agent with the dotgui skill installed (via gui setup) can write a .gui file directly from a prompt: Figma is one entry point among several, not a requirement.' },
      { q: 'What gets preserved when exporting a Figma design to .gui?', a: 'The Figma plugin is coming soon (in review). Once live, it will preserve auto-layout, fills, gradients, effects, and design tokens: a 1:1 mapping of Figma’s own layer model, not an approximation.' },
      { q: 'Can I open a .gui file back in Figma after an agent edits it?', a: 'That’s the eventual point of the format: the same file is legible to a design tool and an agent, so it can move in either direction. The Figma plugin that enables this is coming soon.' },
      { q: 'Does reading a .gui file require an MCP connection to Figma?', a: 'No. Once a design is exported to .gui, it’s a static file: no live connection, API calls, or access to Figma’s servers required to read it.' }
    ],
    related: ['vs-screenshots', 'vs-css', 'prompting-your-agent']
  },
  {
    slug: 'vs-screenshots',
    category: 'vs',
    navLabel: '.gui vs a screenshot',
    title: '.gui vs a screenshot or PNG mockup',
 dek: 'A picture is a dead end: an agent has to guess spacing, hierarchy, and color from pixels. A .gui file hands those values over directly, already structured.',
 seoTitle: '.gui vs a screenshot mockup: why a file, not pixels | .gui Guides',
 seoDescription: 'A PNG mockup has no structure: an agent regenerating from it has to guess layout, spacing, and color from pixels. A .gui file preserves those values as literal, editable data.',
    datePublished: '2026-07-10',
    dateModified: '2026-07-10',
    body: [
      { type: 'p', text: 'A mockup is a picture. However it was made (Figma export, a hand-drawn comp, a screenshot of a competitor’s app) once it’s a PNG, the structure that produced it is gone. An agent asked to build from it has to reverse-engineer spacing, hierarchy, and exact colors from pixels: is that gap 16px or 20px? Is that gray <code>#F5F5F5</code> or <code>#F4F4F4</code>? Nothing in a screenshot answers that with certainty.' },
      { type: 'h2', text: 'Structure survives, instead of being reverse-engineered' },
      { type: 'p', text: 'A <code>.gui</code> file keeps the values that produced the picture, not just the picture. A <code>gap="16"</code> attribute is unambiguous in a way that a rendered 16px visual gap in a PNG is not. A <code>fill="$surface"</code> token reference tells you a color is intentional and reused, something a screenshot can’t distinguish from a one-off. Editing a <code>.gui</code> file means changing one attribute; editing a mockup to explore a variant usually means regenerating the whole image and hoping the rest stayed consistent.' },
 { type: 'h2', text: 'It still renders to a picture: that part didn’t go away' },
 { type: 'p', text: 'A <code>.gui</code> file always renders to a real preview image too (<code>preview.webp</code>, part of every package): nothing is lost by moving to structured data. The difference is the picture is a byproduct of the file, not the only artifact that exists. An agent, a designer, and a renderer can all work from the same source instead of each starting over from pixels.' },
      { type: 'h2', text: 'Still true as vision models improve' },
 { type: 'p', text: 'A more capable vision model closes some of this gap, but it doesn’t remove the extraction step: reading a screenshot still means inferring structure, spacing, and hierarchy from pixels, a lossy process that can guess wrong with just as much confidence as it guesses right. A <code>.gui</code> file skips extraction entirely: the structure is already data, not something to be reconstructed.' },
 { type: 'p', text: 'That’s what makes <code>.gui</code> work as a design handoff format specifically: export once, and any AI tool downstream reads the actual design, with nothing to reverse-engineer and nothing to hallucinate: the difference between receiving a file and receiving a description of one.' }
    ],
    faq: [
 { q: 'Does a .gui file still have a visual preview like a screenshot?', a: 'Yes: every .gui package includes a preview.webp thumbnail. The difference is that the structured markup that produced it is preserved alongside it, not thrown away.' },
 { q: 'Why can’t an AI agent just work from a screenshot directly?', a: 'It can, but it has to guess exact spacing, hierarchy, and colors from pixels: there’s no way to tell an intentional 16px gap from an accidental 15px one in a raster image. A .gui file states the value directly.' },
 { q: 'Do better vision models make this comparison less relevant?', a: 'Not really: a stronger model still has to run an extraction step to infer structure from pixels, and extraction can produce a confident wrong answer. A .gui file has nothing to extract; the structure is already the data.' }
    ],
    related: ['vs-figma', 'spacing-and-gaps', 'vs-css']
  },
  {
    slug: 'vs-svg',
    category: 'vs',
    navLabel: '.gui vs SVG',
    title: '.gui vs SVG: graphics format vs interface format',
 dek: 'SVG made graphics text. .gui borrows that idea but is purpose-built for interface layout and semantics: things SVG was never designed to express.',
 seoTitle: '.gui vs SVG: same idea, different job | .gui Guides',
    seoDescription: 'SVG describes shapes and paths as readable text but has no layout system or semantic vocabulary for UI. .gui applies SVG’s idea specifically to interfaces: layout, roles, and tokens included.',
    datePublished: '2026-07-10',
    dateModified: '2026-07-10',
    body: [
      { type: 'p', text: 'SVG proved something important: a graphic doesn’t have to be a raster of pixels. It can be readable text (<code>&lt;circle&gt;</code>, <code>&lt;path&gt;</code>, <code>&lt;rect&gt;</code>) that any tool can parse, diff, and edit directly. <code>.gui</code> takes that same premise and applies it to interfaces instead of arbitrary graphics: the way <code>.svg</code> is to graphics, <code>.gui</code> is to UI.' },
      { type: 'h2', text: 'The part they share: a file you open and see' },
      { type: 'p', text: 'Before the differences, the most important thing <code>.gui</code> inherits from SVG is easy to miss because it’s so obvious for SVG: it’s a <strong>standalone, viewable file, not a runtime</strong>. You open an SVG and you see the graphic. There is no framework to install and no code to run first. <code>.gui</code> is built to work the same way: you open the file and you see the interface, because the file already contains everything it needs to be shown (markup, assets, and a rendered <code>preview.webp</code>, all in one package, per <a href="https://github.com/dotgui/core/blob/main/rfcs/0004-package-format.md">RFC-0004</a>). It’s not only a format for moving a design between tools; like an image, it stands on its own. See <a href="/guides/not-a-runtime">.gui is not a runtime</a>. Everything below is about where the two formats diverge after that shared foundation.' },
      { type: 'h2', text: 'Why SVG alone doesn’t cover interfaces' },
 { type: 'p', text: 'SVG has no concept of a layout system: no flex-like <code>row</code>/<code>col</code> with a <code>gap</code>, no responsive behavior, no design tokens, no idea of what a "button" or "nav bar" is. Everything in an SVG is either an absolutely positioned shape or a manually computed path. That’s exactly right for an icon or an illustration, and exactly wrong for a screen that needs to lay itself out, carry semantic roles, and reference reusable tokens.' },
      { type: 'p', text: '<code>.gui</code> adds the layer SVG is missing: <a href="/spec/row"><code>row</code></a>/<a href="/spec/col"><code>col</code></a>/<a href="/spec/grid"><code>grid</code></a> for layout with a real <code>gap</code>, <a href="/spec/tokens">design tokens</a> for values meant to repeat, and a closed <a href="/spec/roles">53-role vocabulary</a> so a node can declare <em>what it is</em> (<code>role="button"</code>), not just how it’s drawn. Shape primitives (<code>rect</code>, <code>ellipse</code>, <code>line</code>) exist in <code>.gui</code> too, so an icon or illustration can sit inside a <code>.gui</code> file natively: it just isn’t the whole story the way it is in SVG.' },
 { type: 'p', text: 'For genuinely complex vector artwork, <code>.gui</code> doesn’t reject SVG outright: an <code>&lt;svg&gt;</code> node can hold raw inline SVG markup directly, with no asset file or indirection needed, specifically so an AI agent that already knows how to write SVG paths can emit a logo or icon in place, in the layout tree, instead of fabricating an asset pipeline for a few shapes (<a href="https://github.com/dotgui/core/blob/main/rfcs/0020-svg-inline-content.md">RFC-0020</a>). SVG is exactly right for that job: it’s just not asked to be the layout language too.' },
      { type: 'h2', text: 'Why .gui is a package, not a single file' },
      { type: 'p', text: 'There’s a second gap SVG leaves for interfaces: a single SVG file has nowhere good to put a real photo. Embedding an actual raster image means either linking an external URL (the file alone no longer carries what it needs, so portability breaks) or inlining it as base64 text, which bloats the file enormously. If an AI model has to pass that file through, it pays the token cost of every base64 character even though the image data is completely opaque to it.' },
      { type: 'p', text: 'That cost is measured, not assumed: in early testing, inlining just two to four images as base64 consumed roughly half the token budget of a multi-hour session converting a file (<a href="https://github.com/dotgui/core/blob/main/rfcs/0004-package-format.md">RFC-0004</a>). Plain path references cost nothing to reference: which is also why <code>.gui</code> skips a separate asset-manifest block entirely: an image just declares <code>src="assets/hero.webp"</code> inline, at the point it appears, the same way HTML, SwiftUI, and Android handle images (<a href="https://github.com/dotgui/core/blob/main/rfcs/0031-images-and-assets.md">RFC-0031</a>).' },
      { type: 'p', text: 'That’s one of the two reasons <code>.gui</code> is defined as a zip package rather than a flat text file: real image files sit in an <code>assets/</code> folder alongside the markup, referenced by a plain relative path. See <a href="/guides/vs-screenshots">.gui vs a screenshot</a> for why keeping the structure itself (not just the image) is the bigger point.' }
    ],
    faq: [
 { q: 'Can I put SVG shapes inside a .gui file?', a: '.gui has its own shape primitives (rect, ellipse, line) that cover the same ground for icons and simple graphics. For more complex artwork, an <svg> node can also hold raw inline SVG markup directly, no asset file required.' },
 { q: 'Why not just extend SVG with a layout system instead of a new format?', a: 'SVG’s design targets arbitrary vector graphics, not application interfaces: it has no concept of roles, tokens, or a UI-shaped element vocabulary. .gui borrows SVG’s "readable text, not pixels" idea but is purpose-built for UI from the ground up.' },
      { q: 'Why is .gui a zip package instead of a single text file like SVG?', a: 'Mainly to keep real images as real files instead of inlined base64 text. Testing found that inlining a handful of images as base64 could consume roughly half the token budget of a long AI session: a plain path reference into the package’s assets/ folder costs almost nothing by comparison.' }
    ],
    related: ['vs-html', 'vs-css', 'layout-row-col-grid']
  },

  // ── Best practices ───────────────────────────────────────────────────────
  {
    slug: 'prompting-your-agent',
    category: 'practice',
    navLabel: 'Prompting your agent',
    title: 'Prompting your AI agent to build a .gui file',
    dek: 'gui setup teaches your own agent the format. Here’s the mental model and what to actually say.',
    seoTitle: 'How to prompt an AI agent to build a UI in .gui | .gui Guides',
    seoDescription: 'How to get Claude Code, Cursor, or Gemini CLI to design a UI as a .gui file: install the skill with gui setup, the agent → skill → gui mental model, and what to say.',
    datePublished: '2026-07-10',
    dateModified: '2026-07-10',
    body: [
 { type: 'p', text: '<strong>.gui contains no AI.</strong> The CLI and the reference engine are 100% deterministic: validation, rendering, and scoring, zero model calls, by design (<a href="https://github.com/dotgui/core/blob/main/rfcs/0010-no-ai-in-pipeline.md">RFC-0010</a>): a deterministic pipeline is one an agent can trust to mean exactly what it says. The actual design generation happens in <strong>your own agent</strong>: Claude Code, Gemini CLI, Cursor, Codex, whatever you already use. <code>gui setup</code> installs the dotgui skill into that agent, so when you ask it to build something, it already knows the format instead of guessing at markup.' },
      { type: 'h2', text: 'The mental model' },
      { type: 'code', lang: 'text', label: 'The loop', code: 'you ──ask──▶ your agent ──uses──▶ dotgui skill ──calls──▶ gui (this tool)' },
      { type: 'p', text: 'You ask in plain language. The skill tells your agent the format’s vocabulary, conventions, and pitfalls (see <a href="/guides/common-agent-mistakes">Common agent mistakes</a>). The agent writes <code>design.guix</code> markup directly, then calls the <code>gui</code> CLI to validate and package it: <code>gui</code> never designs anything itself, it only checks and packages what the agent wrote.' },
      { type: 'h2', text: 'Getting started' },
      { type: 'code', lang: 'bash', label: 'One-time setup', code: 'npm i -g @dotgui/cli\ngui setup   # installs the dotgui skill into detected agents' },
      { type: 'p', text: '<code>gui setup</code> asks for one confirmation and installs into each detected agent’s skill directory (e.g. <code>~/.claude/skills/dotgui/</code>). After that, a plain-language ask is enough.' },
      { type: 'h2', text: 'What to actually say' },
 { type: 'callout', tone: 'do', text: 'Say what the screen is for and let the agent choose structure: "a stocks watchlist screen, dark mode, one card per holding." The skill already knows the vocabulary: you don’t need to write markup yourself.' },
 { type: 'callout', tone: 'dont', text: 'Don’t ask for "a screenshot" or "a mockup image" of the UI: that sends the agent toward pixels instead of a .gui file, and you lose everything covered in vs a screenshot or PNG mockup.' },
 { type: 'callout', tone: 'do', text: 'If you already have a reference (a competitor’s screen, a Figma file, a hand sketch) hand it over and ask for a .gui file built from it. The skill handles translating intent into the format’s elements, roles, and tokens.' },
      { type: 'p', text: 'Once you have a file, iteration is just more asks: "make the balance number larger," "use the brand token for the CTA fill." Each change is a targeted edit to the existing file, not a regeneration from scratch.' }
    ],
    faq: [
 { q: 'Does gui setup work with any AI coding agent?', a: 'It installs the dotgui skill into detected agents: Claude Code, Gemini CLI, Cursor, Codex, and others with a skill/plugin model. For agents without one, it prints the format snippet to add manually.' },
 { q: 'Does the gui CLI itself generate designs?', a: 'No: the CLI and engine are 100% deterministic, zero AI. Your own agent does the designing; gui only reads, validates, lints, renders, and packages the result.' },
 { q: 'What should I say to my agent to get a .gui file instead of a mockup image?', a: 'Just ask for what the screen is for in plain language: after gui setup, the skill already tells the agent to produce a .gui file. Avoid asking for a "screenshot" or "image," which points the agent at pixels instead of structured markup.' }
    ],
    related: ['common-agent-mistakes', 'spacing-and-gaps', 'vs-screenshots']
  },
  {
    slug: 'common-agent-mistakes',
    category: 'practice',
    navLabel: 'Common agent mistakes',
    title: 'Common mistakes AI agents make in .gui files',
    dek: 'An agent that hasn’t been taught the format brings habits over from HTML and CSS that don’t belong in .gui. Here are the five that show up most.',
    seoTitle: 'Common AI agent mistakes in .gui files | .gui Guides',
    seoDescription: 'The habits AI agents carry over from HTML/CSS that don’t belong in .gui: fake spacer rows instead of gap, hardcoded colors instead of tokens, missing role=, and more.',
    datePublished: '2026-07-10',
    dateModified: '2026-07-10',
    body: [
      { type: 'p', text: 'An agent that generates <code>.gui</code> without the dotgui skill installed (see <a href="/guides/prompting-your-agent">Prompting your agent</a>) will often fall back on HTML/CSS habits that technically validate but miss what the format is actually for. These are the five that show up most.' },
      { type: 'h2', text: '1. Faking spacing with an empty row' },
 { type: 'callout', tone: 'dont', text: 'Adding an empty <col height="16"/> between two elements to create visual space: a leftover habit from table-based HTML layout.' },
      { type: 'callout', tone: 'do', text: 'Use the gap attribute on the parent row or col. One declared number, no dead markup. Full explanation in Spacing and gaps.' },
      { type: 'h2', text: '2. Hardcoding colors instead of using tokens' },
      { type: 'p', text: 'Repeating the same literal <code>fill="#2B6BE4"</code> across a dozen nodes instead of declaring it once as a <a href="/spec/tokens">token</a> and referencing <code>$brand</code>. This directly costs points on the <strong>Consistent</strong> level of <a href="/spec/quality">CCAC scoring</a>: a file that hand-repeats a value doesn’t agree with itself the way a token-backed one does.' },
      { type: 'h2', text: '3. Skipping role= entirely' },
      { type: 'p', text: 'Leaving structural nodes without a <a href="/spec/roles"><code>role=</code></a> anchor. It costs nothing to add and it’s the entire basis of the <strong>Comprehensible</strong> CCAC level: a button without <code>role="button"</code> is invisible to any tool trying to read the file’s semantics, not just to a human. Roles are declared, not inferred, on purpose: only the author (or the agent writing the file) actually knows a subtree is a nav-bar rather than a breadcrumb trail that happens to look similar (<a href="https://github.com/dotgui/core/blob/main/rfcs/0041-role-attribute.md">RFC-0041</a>).' },
      { type: 'h2', text: '4. Over-nesting containers' },
 { type: 'p', text: 'Wrapping a <code>row</code> inside a <code>col</code> inside a <code>frame</code> when a single <code>row</code> would do: an old defensive-div habit. Extra nesting with no layout purpose is exactly what the <strong>Clean</strong> CCAC level flags as waste.' },
      { type: 'h2', text: '5. Forgetting the assets folder' },
      { type: 'p', text: 'Referencing an <code>img</code> <code>src</code> that doesn’t point to a real file inside the package’s <code>assets/</code> folder. A file can be syntactically valid and still be broken this way: the <strong>Intact</strong> gate (part of CCAC’s scoring gate) exists specifically to catch it.' }
    ],
    faq: [
      { q: 'Why do AI agents fake spacing with empty elements in .gui?', a: 'It’s a carried-over habit from HTML/CSS, where an invisible spacer element is a common (if outdated) way to force a gap. .gui’s row and col elements take a literal gap attribute instead, so the workaround is unnecessary.' },
 { q: 'Does a hardcoded color still produce a valid .gui file?', a: 'Yes: it validates fine. But it costs points on the Consistent CCAC level, since the file doesn’t agree with itself the way a token-backed value does, and it makes global color changes harder to make correctly.' },
 { q: 'What happens if role= is left off a node?', a: 'The file still validates and renders: role is optional structurally. But it’s the entire basis of the Comprehensible CCAC level, so leaving it off means the node is invisible to any tool or agent trying to read the file’s semantics.' }
    ],
    related: ['spacing-and-gaps', 'ccac-score', 'prompting-your-agent']
  },
  {
    slug: 'spacing-and-gaps',
    category: 'practice',
    navLabel: 'Spacing and gaps',
    title: 'Spacing in .gui: use gap, not an empty row',
 dek: 'The single most common habit agents bring over from HTML/CSS: and the one-attribute fix.',
    seoTitle: 'Spacing in .gui files: gap vs empty spacer rows | .gui Guides',
    seoDescription: 'Why AI agents fake spacing in .gui with empty spacer rows, why it’s wrong, and how the gap attribute on row/col/stack replaces it with one declared value.',
    datePublished: '2026-07-10',
    dateModified: '2026-07-10',
    body: [
      { type: 'p', text: 'A pattern shows up constantly in AI-generated <code>.gui</code> files: an empty element sitting between two real ones, existing only to create visual space.' },
      { type: 'code', lang: 'xml', label: 'Don’t', code: '<col>\n  <text>Balance</text>\n  <col height="16"/>   <!-- fake spacer -->\n  <text>$4,204.10</text>\n</col>' },
      { type: 'p', text: 'It renders correctly, and it will pass a naive visual check against a reference design. It is still wrong, for two concrete reasons: it’s dead markup with no semantic purpose (a node that exists purely as a workaround), and it’s brittle: change the parent’s padding or add a third child and the spacing math has to be redone by hand at every spacer.' },
      { type: 'h2', text: 'The fix: gap' },
 { type: 'p', text: '<a href="/spec/row"><code>row</code></a>, <a href="/spec/col"><code>col</code></a>, and <a href="/spec/grid"><code>grid</code></a> all take a <code>gap</code> attribute: the space between every child, declared once on the parent.' },
      { type: 'code', lang: 'xml', label: 'Do', code: '<col gap="16">\n  <text>Balance</text>\n  <text>$4,204.10</text>\n</col>' },
      { type: 'p', text: 'One number, on the container that actually owns the spacing decision. Add a third child and the gap still applies correctly with no extra markup. This isn’t a style preference: it’s the difference between a value the file can be reasoned about and a value that has to be reverse-engineered from node heights.' },
      { type: 'h2', text: 'Why agents default to the old pattern' },
      { type: 'p', text: 'It’s inherited from HTML, where a real <code>gap</code> property only reliably exists in flex/grid layout contexts and plenty of training data still comes from table-layout-era markup or naive absolute positioning, where an invisible spacer was the only tool available. <code>.gui</code>’s layout elements always support <code>gap</code>: there’s never a context where the workaround is actually necessary, so an agent that reaches for it either hasn’t been told the format has <code>gap</code>, or is pattern-matching from HTML habit. <code>gui setup</code> installs a skill that teaches this explicitly (see <a href="/guides/prompting-your-agent">Prompting your agent</a>).' },
      { type: 'h2', text: 'It also affects your score' },
 { type: 'p', text: 'A dead spacer node is exactly what the <strong>Clean</strong> level of <a href="/spec/quality">CCAC scoring</a> flags: unused markup with no layout purpose. Swapping it for <code>gap</code> is a direct, mechanical fix, not a matter of taste.' }
    ],
    faq: [
 { q: 'Which elements support the gap attribute?', a: 'row, col, and grid: every .gui layout container that arranges children in a direction or track system takes a literal gap attribute for the space between them.' },
      { q: 'Is an empty spacer element ever necessary in .gui?', a: 'No. row, col, and grid always support gap, so there’s no layout situation in .gui that requires a dead spacer node the way older HTML table-layout patterns sometimes did.' },
 { q: 'Does a fake spacer row break validation?', a: 'No, it still validates and renders correctly: which is exactly why it’s easy to miss. It does cost points on the Clean level of CCAC scoring as unused markup.' }
    ],
    related: ['common-agent-mistakes', 'vs-css', 'ccac-score']
  },
  {
    slug: 'ccac-score',
    category: 'practice',
    navLabel: 'Improving your CCAC score',
    title: 'How to get a good CCAC score',
    dek: 'The four levels explained on /spec/quality, turned into concrete things to actually go fix.',
    seoTitle: 'How to improve a .gui file’s CCAC score | .gui Guides',
 seoDescription: 'Practical fixes for each CCAC level (Clean, Consistent, Accessible, Comprehensible) so a .gui file scores well: remove dead markup, use tokens, fix contrast, declare roles.',
    datePublished: '2026-07-10',
    dateModified: '2026-07-10',
    body: [
      { type: 'p', text: 'The <a href="/spec/quality">CCAC model</a> explains what the score measures. This is the companion piece: what to actually change in a file to move each number, assuming a file has already cleared the <strong>Valid + Intact</strong> gate (a file that fails either isn’t scored at all).' },
 { type: 'h2', text: 'Clean: remove waste' },
 { type: 'list', items: ['Delete nodes with no layout or visual purpose: the classic case is an empty spacer element; see Spacing and gaps.', 'Flatten unnecessary nesting: a row wrapped in a col wrapped in a frame, where one container would do.', 'Remove declared tokens or styles that nothing in the file actually references.'] },
 { type: 'h2', text: 'Consistent: agree with yourself' },
 { type: 'list', items: ['Replace repeated literal values (a color, a spacing number used five times) with a single declared token, referenced everywhere.', 'Pick one system and stay in it: don’t mix ad hoc pixel values with token references for the same kind of value across the file.'] },
 { type: 'h2', text: 'Accessible: stay legible' },
 { type: 'list', items: ['Check text-to-background contrast against WCAG 2.2 visual criteria, particularly on colored fills and overlays.', 'Keep tap targets (buttons, interactive rows) at a real minimum size: a role="button" that’s visually tiny still fails this even though it validates.', 'Don’t drop text size below what the criteria allow for body copy.'] },
 { type: 'h2', text: 'Comprehensible: be readable by a machine' },
 { type: 'list', items: ['Add role= to every structural node it applies to, from the closed 53-role vocabulary: a button without role="button" scores as if it isn’t one.', 'Prefer the most specific correct role over a generic one when the vocabulary has it.', 'Understand the score is reach-coverage, not a flat tag-everything ratio: each declared role documents its own subtree as far as its catalog-defined reach allows. A self-contained widget’s reach covers everything inside it; a card’s reach covers one chrome level before its contents need their own roles. A few roles placed on the right nodes can legitimately cover a large share of the tree.'] },
 { type: 'p', text: 'None of this is a gate: <a href="/spec/quality">a low score is still a valid, packable file</a>. The score is a diagnostic, not a blocker; treat a low number as a punch list, not a rejection. The scoring model (<a href="https://github.com/dotgui/core/blob/main/rfcs/0040-quality-scoring-model.md">RFC-0040</a>) and the role vocabulary it reads (<a href="https://github.com/dotgui/core/blob/main/rfcs/0041-role-attribute.md">RFC-0041</a>) both document the exact mechanics if you want the full reasoning.' }
    ],
    faq: [
      { q: 'Do I need a perfect CCAC score to ship a .gui file?', a: 'No. A low score still describes a valid, packable file: the score is advisory, not a gate. Any pass/fail threshold is a decision made by whatever tool consumes the score, not by the format itself.' },
 { q: 'What’s the fastest single fix to improve a low score?', a: 'Usually adding role= to structural nodes (Comprehensible) or swapping repeated literal values for tokens (Consistent): both are mechanical changes, not redesigns, and both move the number directly.' },
 { q: 'Does Comprehensible require tagging every single node with a role?', a: 'No: it’s reach-coverage, not full coverage. Each declared role documents its own subtree as far as its catalog-defined reach allows (a self-contained widget’s reach covers everything inside it; a card’s reach covers one chrome level before its payload needs its own roles), so a handful of well-placed roles can cover a large share of the tree without individually tagging every node.' }
    ],
    related: ['common-agent-mistakes', 'spacing-and-gaps', 'avoiding-generic-ui']
  },
  {
    slug: 'layout-row-col-grid',
    category: 'practice',
    navLabel: 'row vs col vs grid',
    title: 'Structuring a screen: row vs col vs grid',
    dek: 'Three layout elements cover almost every screen. Here’s how to pick between them without guessing.',
 seoTitle: 'row vs col vs grid in .gui: which to use | .gui Guides',
 seoDescription: 'A decision guide for .gui’s layout elements: row for horizontal arrangement, col for vertical, grid for fixed multi-track layouts like card galleries: with examples.',
    datePublished: '2026-07-10',
    dateModified: '2026-07-10',
    body: [
      { type: 'p', text: 'Most screens are built from three layout elements. Picking the right one is mostly about which direction the content actually flows in: not a stylistic choice.' },
 { type: 'h2', text: 'row and col: direction' },
      { type: 'p', text: '<a href="/spec/row"><code>row</code></a> arranges children left to right; <a href="/spec/col"><code>col</code></a> arranges children top to bottom. Both belong to the same underlying stack family and both take <code>gap</code> and standard spacing/alignment attributes (see <a href="/guides/spacing-and-gaps">Spacing and gaps</a>). Default to whichever matches the actual reading direction of the content: a settings list is a <code>col</code> of rows; a button toolbar is a <code>row</code>.' },
      { type: 'code', lang: 'xml', label: 'A settings screen: col of rows', code: '<col gap="12">\n  <row gap="8" role="list-item">\n    <text>Notifications</text>\n  </row>\n  <row gap="8" role="list-item">\n    <text>Privacy</text>\n  </row>\n</col>' },
 { type: 'h2', text: 'grid: fixed multi-track layout' },
 { type: 'p', text: 'Reach for <a href="/spec/grid"><code>grid</code></a> when content repeats across more than one axis at once: a photo gallery, a dashboard of cards, anything that would otherwise be a <code>row</code> of <code>col</code>s (or vice versa) faked to look like a grid. <code>grid</code> takes its own track and <code>gap</code> attributes and expresses the two-axis relationship directly instead of nesting stacks to fake it.' },
      { type: 'code', lang: 'xml', label: 'A card gallery: grid, not nested rows', code: '<grid columns="3" gap="16">\n  <rect role="card"/>\n  <rect role="card"/>\n  <rect role="card"/>\n</grid>' },
      { type: 'h2', text: 'A quick rule of thumb' },
      { type: 'table', head: ['Content shape', 'Use'], rows: [
        ['One direction, one axis (a list, a toolbar)', '<code>row</code> or <code>col</code>'],
        ['Repeats across rows and columns at once', '<code>grid</code>'],
        ['A fixed positioned container or canvas root', '<code>frame</code>']
      ] },
 { type: 'p', text: 'Nesting a <code>row</code> inside a <code>col</code> to fake a grid is exactly the kind of over-nesting the <strong>Clean</strong> CCAC level penalizes (see <a href="/guides/common-agent-mistakes">Common agent mistakes</a>): if the content is genuinely two-axis, <code>grid</code> is the correct element, not a workaround.' }
    ],
    faq: [
 { q: 'When should I use grid instead of nesting row and col?', a: 'When content repeats across two axes at once (a card gallery, a dashboard) grid expresses that directly. Nesting row inside col to fake the same layout is unnecessary and gets flagged as over-nesting by the Clean CCAC level.' },
 { q: 'What’s the difference between row/col and the stack family mentioned in the spec?', a: 'row and col are the two directional members of the same underlying stack family: row lays out left to right, col lays out top to bottom. Both share the same spacing and alignment attributes.' }
    ],
    related: ['spacing-and-gaps', 'common-agent-mistakes', 'vs-svg']
  },
  {
    slug: 'avoiding-generic-ui',
    category: 'practice',
    navLabel: 'Avoiding generic AI UI',
    title: 'Making AI-generated UI not look generic',
    dek: 'The tells of an unedited AI-generated screen, and the structural (not aesthetic) fixes .gui makes available.',
    seoTitle: 'Avoiding generic-looking AI-generated UI in .gui | .gui Guides',
 seoDescription: 'The recognizable tells of unedited AI-generated interfaces (default gradients, uniform spacing, generic type) and the structural .gui fixes: real tokens, a deliberate type scale, and roles.',
    datePublished: '2026-07-10',
    dateModified: '2026-07-10',
    body: [
      { type: 'p', text: 'Unedited AI-generated interfaces tend to converge on the same handful of tells: a purple-to-blue gradient with no relationship to the product, fully rounded pill buttons everywhere regardless of size, one spacing value (usually 16px) reused for every gap with no rhythm, and a single generic type scale with no real hierarchy. None of this is a <code>.gui</code> problem specifically: it’s what happens when a model defaults instead of deciding. But <code>.gui</code>’s structure makes the fix mechanical rather than vague.' },
      { type: 'h2', text: 'Replace default fills with a real token palette' },
      { type: 'p', text: 'A generic gradient is usually a placeholder nobody committed to. Define <a href="/spec/tokens">tokens</a> that came from the actual product (a brand color, a real neutral scale) and reference them everywhere instead of leaving default fills in place. This is the same fix that improves <strong>Consistent</strong> scoring in <a href="/guides/ccac-score">CCAC</a>: one committed system beats several undecided ones.' },
      { type: 'h2', text: 'Give spacing a scale, not one number' },
 { type: 'p', text: 'Uniform 16px everywhere is a tell precisely because real interfaces don’t space everything identically: related items sit closer together than unrelated sections. Use a small set of deliberate <code>gap</code> values (say 4 / 8 / 16 / 32) and apply the smaller ones inside a group and the larger ones between groups, instead of one value applied everywhere by default.' },
      { type: 'h2', text: 'Use role= to make hierarchy structural, not just visual' },
      { type: 'p', text: 'Generic UI often has visual hierarchy (a bigger font here, a bolder weight there) with nothing underneath it. Declaring <a href="/spec/roles"><code>role=</code></a> on headings, primary actions, and key content makes the hierarchy a structural fact of the file, not just a font-size choice: and it’s the same signal that improves <strong>Comprehensible</strong> scoring.' },
 { type: 'p', text: 'None of this requires design taste to execute: it requires actually deciding on a token set and a spacing scale instead of accepting whatever a model defaulted to, and the closed vocabulary makes it possible to check that those decisions were actually applied consistently across the file.' }
    ],
    faq: [
 { q: 'Why does AI-generated UI often look the same regardless of tool?', a: 'It converges on defaults instead of decisions (the same gradient, the same uniform spacing value, the same generic type scale) because nobody committed to a real token set or spacing scale for the specific product.' },
 { q: 'Can .gui’s quality score catch a generic-looking design?', a: 'CCAC scores the file, not the design’s taste: it won’t flag "boring" directly. But undecided defaults usually show up as inconsistency (repeated literal values instead of a token system), which the Consistent level does catch.' }
    ],
    related: ['ccac-score', 'vs-css', 'common-agent-mistakes']
  },

  // ── Concepts ─────────────────────────────────────────────────────────────
  {
    slug: 'not-a-runtime',
    category: 'concepts',
    navLabel: '.gui is not a runtime',
    title: '.gui is not a runtime: it’s a file you open and see',
    dek: 'The most common misread is that .gui is another framework you have to set up and run. It isn’t. Like an image, a .gui file stands on its own: you open it and see the interface, with no runtime required.',
    seoTitle: '.gui is not a runtime: a standalone file format | .gui Guides',
    seoDescription: 'Why .gui is a self-contained file format, not a framework or runtime. Like SVG or PDF, a .gui file carries everything it needs to be viewed on its own: you open it and see the UI, with nothing to install or wire up.',
    datePublished: '2026-07-29',
    dateModified: '2026-07-29',
    body: [
      { type: 'p', text: 'Almost every skeptical question about <code>.gui</code> ("so it’s XAML?", "why not just HTML?", "isn’t this another framework?") comes from one wrong assumption: that <code>.gui</code> is a <strong>runtime</strong> you have to set up, wire together, and execute to get anything out of. It isn’t. The single sentence that resolves most of the confusion is this: <strong>.gui is a file format, not a runtime. It’s something you open and see, the way you open an image.</strong>' },
      { type: 'h2', text: 'Two things a runtime makes you do that .gui doesn’t' },
      { type: 'p', text: 'A runtime (a browser running HTML/CSS/JS, the .NET stack running XAML, Qt running QML) asks two things of you before you can see a UI. First, <strong>set it up</strong>: install the framework, its toolchain, its dependencies, a dev server. Second, <strong>execute it</strong>: the interface only exists after code runs, and it can render differently depending on timing, data, or a script that hasn’t finished (<a href="/guides/vs-html">.gui vs HTML</a>). A <code>.gui</code> file asks for neither. There is nothing to install and no code to run, because the file already <em>is</em> the interface, sitting there fully described.' },
      { type: 'h2', text: 'It behaves like an image, not like source code' },
      { type: 'p', text: 'This is the part the "interchange format" framing undersells. Yes, <code>.gui</code> moves cleanly between tools, but it isn’t only a courier that’s meaningless until some other tool ingests it. It’s a <strong>standalone artifact</strong>, the way <code>.png</code>, <code>.pdf</code>, and <code>.svg</code> are. You don’t "set up" a PNG; you open it and see the picture. You don’t compile a PDF; you open it and read it. A <code>.gui</code> file is meant to work the same way: double-click it, and you see the interface, because the file already contains everything it needs to be shown (the <code>design.guix</code> markup, the <code>assets/</code> folder, and a rendered <code>preview.webp</code> thumbnail, all in one package, per <a href="https://github.com/dotgui/core/blob/main/rfcs/0004-package-format.md">RFC-0004</a>).' },
      { type: 'callout', tone: 'do', text: 'The right mental model: .gui is to interfaces what SVG is to graphics and PDF is to documents, a self-contained file you view directly that also happens to be editable and convertible. "You open it and you see it" is the whole promise.' },
      { type: 'p', text: 'The reason it can behave like an image is <em>precisely because</em> it isn’t a runtime. A file that runs no logic and depends on no framework has a single, fixed appearance, so a viewer can just show it, with no execution step in between (<a href="/guides/intent-vs-geometry">Intent vs geometry</a>). The reference renderer, the one-line <a href="/embed"><code>&lt;gui-embed&gt;</code></a> script, and any future native previewer are all just <em>viewers</em> for a file that already knows what it looks like, the same role a PDF reader plays for a PDF, not the role a browser plays for a web app.' },
      { type: 'h2', text: 'Then what are the CLI, kit, and embed for?' },
      { type: 'p', text: 'Reasonable question, since they look like "setup." They aren’t required to <em>view</em> a file; they’re optional tools for <em>producing and embedding</em> one. The <a href="/cli">CLI</a> validates and packages a file an agent wrote; <a href="/kit">the kit</a> lets a third-party app read and render <code>.gui</code>; <a href="/embed">embed</a> drops a viewer onto a web page with one script tag. None of them is a runtime the file depends on to exist, the way a React app depends on React. Take them all away and the file is still a complete, viewable description of an interface; it just wouldn’t have a fancy viewer wrapped around it yet.' },
      { type: 'h2', text: 'Why this matters for where the format is going' },
      { type: 'p', text: 'The end state is the one every standalone file format reached: a <code>.gui</code> file is as easy to open as a <code>.png</code>. You get one from an AI agent, from a design tool export, or from a teammate, and you see it immediately; then, if you want, you edit it, version it, or convert it to code. "Interchange" is one thing it’s good for. "Stands on its own" is what makes it a format at all, rather than an intermediate representation that only exists in transit between two other tools.' }
    ],
    faq: [
      { q: 'Do I need to install or set anything up to view a .gui file?', a: 'No. A .gui file is self-contained: it carries its markup, assets, and a rendered preview in one package, so viewing it is like opening an image or a PDF. You open it and see the interface, with no framework, toolchain, or dev server to set up. The CLI, kit, and embed library are optional tools for producing or embedding files, not a runtime the file depends on to exist.' },
      { q: 'Is .gui a framework or a runtime like React, XAML, or Qt?', a: 'No. Those are runtimes: you install them, and the UI only exists after their code executes. .gui runs no logic and depends on no framework, so the file already is the interface, with a single fixed appearance. That is exactly why it can behave like an image you open and see, rather than source code you have to build and run.' },
      { q: 'If it’s standalone like an image, why do you call it an interchange format?', a: 'It’s both, and the two are related. Because a .gui file is self-contained and runs no logic, it has one fixed appearance any viewer can show directly: that’s the "standalone, open it and see it" property. And because it’s open text that no single tool owns, it also moves cleanly between AI models, design tools, and code: that’s the interchange property. Standing alone is what makes it a real format; interchange is one of the things that format is good for.' }
    ],
    related: ['vs-html', 'vs-xaml', 'what-problem']
  },
  {
    slug: 'what-problem',
    category: 'concepts',
    navLabel: 'What problem it solves',
    title: 'What problem does .gui actually solve?',
    dek: 'The honest version: .gui isn’t trying to replace HTML, CSS, or your design tool. It adds one missing thing: a portable, throwaway design layer for the AI era.',
    seoTitle: 'What problem does .gui solve? | .gui Guides',
    seoDescription: 'Why a portable UI file format matters now: an open ideation layer where an AI agent can generate, compare, and discard interface ideas as single files before they reach your codebase or design tool.',
    datePublished: '2026-07-29',
    dateModified: '2026-07-29',
    body: [
      { type: 'p', text: 'The fair skeptic’s question, asked several ways when the format was first shown publicly, is "what problem does this solve that HTML, CSS, or Figma don’t already?" HTML is as simple as it gets; design tools already exist; AI already writes code. Adding a file format sounds like adding a step. So it’s worth answering directly: <strong>.gui is not a better way to build the final product.</strong> HTML, SwiftUI, and Compose already do that, and <code>.gui</code> doesn’t try to compete with them (<a href="/guides/vs-html">.gui vs HTML</a>). What it adds is a layer that didn’t have an open format before: <strong>disposable design ideation</strong>.' },
      { type: 'h2', text: 'The gap: there’s no cheap unit of "a UI idea"' },
      { type: 'p', text: 'Today an interface idea has to be born as one of two heavy things. Either it’s <strong>code</strong> (which means a repo, a toolchain, a component library, and a design that’s now entangled with an application you have to maintain) or it’s a <strong>design-tool document</strong>, which lives inside one vendor’s app, in a workspace, behind an account. Both are workspaces. Neither is a <em>file</em> you can generate ten of, glance at, keep one, and delete the rest. A screenshot is that cheap, but a screenshot is a dead end: you can’t edit it, render it at a different size, or convert it to code without starting over (<a href="/guides/vs-screenshots">.gui vs a screenshot</a>).' },
      { type: 'p', text: 'A <code>.gui</code> file <em>is</em> that missing cheap unit: one file is one screen, not a workspace. You can ask an agent for six variations of a checkout screen, get six files, compare them side by side, keep one, and throw the rest away, and none of them ever touched your codebase or your production Figma file. That workflow (rapid, low-commitment, before anything is real) is the one the format is actually built for.' },
      { type: 'h2', text: 'Why now, and not five years ago' },
      { type: 'p', text: 'The honest answer to "why didn’t this need to exist before" is that until recently the only things authoring and consuming UIs were humans, and humans were fine with tool-specific formats. Now AI generates and reads interfaces too, and an AI agent wants a <em>structured, textual target it can write directly</em>, not a screenshot it has to reason about visually, and not a full application it has to scaffold to express one screen (<a href="/faq">see the FAQ on AI-readability</a>). The format that fits between "an image" and "a running app" simply had no open standard, the way graphics had none before SVG.' },
      { type: 'h2', text: 'What it is NOT solving' },
      { type: 'callout', tone: 'dont', text: 'It’s not solving "pixel-perfect designer-to-developer handoff." A .gui file is an exchange and ideation artifact, not a guarantee that generated code matches your internal component library. See Handoff, fidelity, and your component library.' },
      { type: 'callout', tone: 'dont', text: 'It’s not solving "build and ship a production app from one file." The final app is still HTML/SwiftUI/Compose. .gui is the source-of-truth design those get built from, not the runtime.' },
      { type: 'callout', tone: 'do', text: 'It IS solving "give an AI agent, a design tool, and a developer one portable thing they can all read, generate, preview, and convert": the interchange gap, not the runtime.' },
      { type: 'p', text: 'If your workflow never generates throwaway design ideas and never moves a design between an AI model, a design tool, and code, it’s reasonable to conclude you don’t have the problem <code>.gui</code> addresses. The format is for the workflow where those handoffs happen constantly and each one currently means a re-authoring step.' }
    ],
    faq: [
      { q: 'Isn’t adding a file format just adding a step to the process?', a: 'Only if you were going to move a design between an AI model, a design tool, and code anyway, which today means re-authoring it at each hop. .gui replaces those re-authoring steps with one portable file, and adds a cheap ideation layer (one file = one screen) that didn’t have an open format before. If your workflow never does those handoffs, you likely don’t need it.' },
      { q: 'Why not just use a single HTML file?', a: 'You can, and for a finished web page you probably should. But an HTML file is a runtime artifact tied to the browser, and using it as a design’s source of truth drags in CSS, a toolchain, and eventual entanglement with an app. .gui is a static, closed-vocabulary file meant to be generated, compared, and discarded cheaply, then converted to HTML (or SwiftUI, or Compose) when you commit.' },
      { q: 'What can .gui do that Figma plus AI can’t already?', a: 'Give you a design as a portable open file instead of a document locked inside one vendor’s workspace. A .gui file can be generated by any AI agent, previewed with one script tag, version-controlled as text, and converted to code, without a Figma account or API in the loop. Figma remains a great place to refine one; .gui is what moves between tools.' }
    ],
    related: ['vs-html', 'vs-xaml', 'handoff-and-fidelity']
  },
  {
    slug: 'intent-vs-geometry',
    category: 'concepts',
    navLabel: 'Intent vs geometry',
    title: 'Does .gui store layout intent or fixed pixels?',
    dek: 'The question that decides whether a UI format is worth having: does it record where things landed, or the rules that put them there? .gui stores intent, which is also its hardest spec problem.',
    seoTitle: 'Layout intent vs absolute geometry in .gui | .gui Guides',
    seoDescription: 'A UI file that stores absolute geometry is just SVG. .gui stores layout intent (stacks, grids, gaps, tokens, and roles) so one file can render across platforms with different layout models.',
    datePublished: '2026-07-29',
    dateModified: '2026-07-29',
    body: [
      { type: 'p', text: 'There’s a sharp version of the "is this just SVG?" critique that’s worth taking head-on: <em>the hard call for any UI format is whether a file stores layout intent or absolute geometry. Store absolute positions and you’ve reinvented SVG. Store intent and you have to commit to one layout model that iOS, Android, and web will each disagree with.</em> That’s exactly the right framing, and <code>.gui</code> chooses <strong>intent</strong>, knowingly, because it’s the only choice that makes the format more than a screenshot with editable text.' },
      { type: 'h2', text: 'What "intent" means concretely' },
      { type: 'p', text: 'A geometry-only file says "this box is at x=16, y=240, 343 wide." An intent file says "these cards are a <a href="/spec/col"><code>col</code></a> with <code>gap=\"16\"</code>, each one full-width, inside a frame with 16 padding." The second form carries the <em>reason</em> the layout looks the way it does, so a renderer on a wider screen, or a different platform, can re-run the rule instead of replaying stale coordinates (<a href="/guides/layout-row-col-grid">row vs col vs grid</a>). <code>.gui</code>’s layout vocabulary (stacks, grids, <code>gap</code>, nine-point <code>align</code> per <a href="https://github.com/dotgui/core/blob/main/rfcs/0012-align-9point.md">RFC-0012</a>, and <a href="/spec/tokens">tokens</a> for values meant to repeat per <a href="https://github.com/dotgui/core/blob/main/rfcs/0005-token-system.md">RFC-0005</a>) exists precisely so the file records rules, not resolved pixels.' },
      { type: 'p', text: 'Semantic <a href="/spec/roles">roles</a> are the same instinct one level up: <code>role=\"nav-bar\"</code> records what a subtree <em>is</em>, not just how it was drawn, so a tool reading the file inherits the author’s intent rather than guessing it back from geometry (<a href="https://github.com/dotgui/core/blob/main/rfcs/0041-role-attribute.md">RFC-0041</a>). A card grid that only carries coordinates will be rebuilt by the next tool as boxes that happen to line up; one that carries "this is a grid, these are cards" can be rebuilt as the same idea.' },
      { type: 'h2', text: 'The honest cost of choosing intent' },
      { type: 'p', text: 'Committing to intent means committing to <em>one</em> layout model, and no single model maps losslessly onto every platform’s engine: flexbox, Auto Layout, and Compose’s modifiers genuinely disagree at the edges. This is the real spec work, and the format doesn’t pretend otherwise. Two design decisions keep it tractable rather than solved-by-fiat: the layout primitives are deliberately a <em>small</em> set (a single <a href="/spec/stack"><code>stack</code></a> with <code>row</code>/<code>col</code>/<code>grid</code> as sugar, per <a href="https://github.com/dotgui/core/blob/main/rfcs/0006-layout-sugar-tags.md">RFC-0006</a>), so there’s less surface for platforms to diverge on; and open edge cases are worked out in public RFCs rather than hidden in a reference implementation, so the grid system’s unresolved corners, for instance, are argued out in <a href="https://github.com/dotgui/core/blob/main/rfcs/0032-grid-system.md">RFC-0032</a>.' },
      { type: 'p', text: 'The precedent the format follows on purpose is the one that already survived this: the layout model that gets nailed down is defined by the <em>renderer conformance corpus</em>, not by prose in the spec. Where GTK’s <code>.ui</code>, QML, and XAML each kept a single reference implementation and let platforms diverge silently, the intent-vs-geometry line only holds if "what this layout means" is pinned by shared pass/fail fixtures every renderer must agree on (<a href="/guides/roadmap">Versioning and the conformance corpus</a>).' },
      { type: 'h2', text: 'So: SVG or not?' },
      { type: 'p', text: 'Not SVG, because SVG is the geometry answer by design: it has shapes and absolute paths and no concept of a layout that re-runs (<a href="/guides/vs-svg">.gui vs SVG</a>). <code>.gui</code> pays a real price for taking the intent side of the fork (a layout model it has to defend across platforms), and that price is the whole reason the format is useful instead of being SVG with extra tags.' }
    ],
    faq: [
      { q: 'Does a .gui file store absolute x/y coordinates?', a: 'No, not as the primary model. It stores layout intent (stacks, grids, gaps, alignment, tokens, and roles) so a renderer re-runs the layout rule per platform and screen size instead of replaying fixed coordinates. Absolute positioning exists where a design genuinely needs it, but it isn’t how the format describes ordinary layout.' },
      { q: 'If it stores intent, how can iOS, Android, and web all render it the same?', a: 'By pinning what each layout construct means with a shared conformance corpus (pass/fail fixtures every renderer must agree on) rather than leaving it to prose. That’s the lesson from SVG and HTML, which shipped huge test suites, versus XAML/QML/GTK .ui, which kept single reference implementations and diverged. It’s the format’s hardest, most deliberate work.' },
      { q: 'Doesn’t committing to one layout model make .gui opinionated?', a: 'Yes, deliberately. A small, opinionated set of primitives (stack/row/col/grid with gap and nine-point align) is what lets the same file mean the same thing across tools. The alternative, exposing every platform’s full layout API, would make files unportable, which defeats the point of an interchange format.' }
    ],
    related: ['vs-svg', 'vs-xaml', 'roadmap']
  },
  {
    slug: 'roadmap',
    category: 'concepts',
    navLabel: 'Versioning & roadmap',
    title: 'Versioning, interactivity, and the conformance corpus',
    dek: 'Where the format is (v0.2), where it’s going (v1.0 visual completeness, v2.0 motion), and the honest answer to "the ecosystem is the existential question."',
    seoTitle: '.gui roadmap: versioning, interactivity, conformance | .gui Guides',
    seoDescription: 'How .gui versions itself: the 0.x line stabilizes the visual format toward v1.0, motion and interactivity are planned for v2.0, and a public conformance corpus is what keeps renderers from diverging.',
    datePublished: '2026-07-29',
    dateModified: '2026-07-29',
    body: [
      { type: 'p', text: 'Two of the most substantive questions raised about the format weren’t about syntax. They were about time and trust: <em>does it handle component state and interactivity?</em> and <em>the ecosystem is the existential question, not the spec.</em> Both are fair, and both have the same shape of answer: a deliberate order of operations, published in the open, rather than a promise everything already works.' },
      { type: 'h2', text: 'Where the format is: v0.2, visual first' },
      { type: 'p', text: 'The current spec (v0.2) already covers the visual building blocks: <a href="/spec">frames, stacks, grids, text, images, shapes</a>, <a href="/spec/tokens">tokens</a>, styles, variants, fonts, effects, and light/dark modes. The whole point of the 0.x line is to <em>find what’s still missing on the visual side</em> and close it, so that v1.0 can credibly claim to describe any static UI completely. That’s the near-term work: coverage of the visual surface, not new capability categories.' },
      { type: 'h2', text: 'Interactivity and state: planned for v2.0' },
      { type: 'p', text: 'Today <code>.gui</code> describes <strong>components, variants, and styles</strong>, so a button’s hover and pressed <em>appearances</em> can exist as variants, but it does not yet describe <strong>behavior</strong>: what triggers a state change, conditional visibility, data binding, or motion. That’s intentional sequencing, not an oversight. The plan is to stabilize the visual format through v1.0 first, then layer motion and richer interactivity on top in v2.0, the same way SVG settled its static drawing model before SMIL animation was built over it. Designing interactivity before the visual base is stable would mean specifying behavior against a moving target.' },
      { type: 'callout', tone: 'do', text: 'Practical read for today: use .gui for static screens and multi-state appearance (via variants). Don’t expect it to express runtime behavior or animation yet; that’s the v2.0 line.' },
      { type: 'h2', text: 'The ecosystem question, answered honestly' },
      { type: 'p', text: 'The sharpest critique is historical: SVG and HTML won because standards bodies shipped <em>thousands of pass/fail conformance tests</em> alongside reference renderers, so platforms couldn’t diverge silently. XAML, QML, and GTK’s <code>.ui</code> each had a single reference implementation, no public test corpus, and each platform drifted until the format stayed an export target. A UI format’s real spec is its conformance corpus, not its prose, and any serious effort has to ship fixtures (nested grids, RTL, intrinsic sizing) before it ships features.' },
      { type: 'p', text: 'The format takes that seriously rather than waving it off. Two things already point that direction: the engine is <strong>100% deterministic</strong> (validation, rendering, and scoring make zero AI calls, per <a href="https://github.com/dotgui/core/blob/main/rfcs/0010-no-ai-in-pipeline.md">RFC-0010</a>), which is a precondition for reproducible pass/fail tests at all; and every change to the format goes through a <strong>public RFC process</strong> in <a href="https://github.com/dotgui/core">dotgui/core</a>, so the edge cases that break naïve renderers (see <a href="https://github.com/dotgui/core/blob/main/rfcs/0032-grid-system.md">RFC-0032</a> on grids) get argued out in the open before they’re fixed in one implementation’s quirks. The honest status: a growing fixture corpus and a second independent renderer are the work that matters most for the format’s survival, and they’re treated as such, not as something the spec already finished.' },
      { type: 'h2', text: 'What "1.0" will actually mean' },
      { type: 'p', text: 'A credible v1.0 is not "more tags." It’s (1) visual completeness, nothing static a designer needs that the format can’t express, and (2) enough of a conformance corpus that two independent renderers agree on the fixtures. Motion, behavior, and data binding are explicitly deferred to v2.0 so that 1.0 can be a stable, testable, boring foundation. That ordering is the roadmap.' }
    ],
    faq: [
      { q: 'Does .gui support interactivity, component state, or animation today?', a: 'It supports multi-state appearance through components, variants, and styles, so hover/pressed looks can exist as variants, but not runtime behavior, conditional logic, data binding, or motion. Those are planned for v2.0, after the visual format stabilizes at v1.0. Use .gui for static screens today.' },
      { q: 'What is the difference between v1.0 and v2.0 on the roadmap?', a: 'v1.0 is about visual completeness plus a conformance corpus solid enough that independent renderers agree: a stable, testable static format. v2.0 builds motion and richer interactivity on top of that base, the way SVG added animation after its static model was settled.' },
      { q: 'How will .gui avoid the fate of XAML, QML, and GTK .ui?', a: 'By treating the conformance corpus as the real spec. Those formats kept single reference implementations and no public test suite, so platforms diverged silently. .gui’s engine is fully deterministic (a precondition for reproducible tests) and its changes go through public RFCs; a shared fixture corpus and a second independent renderer are treated as the format’s most important work, not an afterthought.' }
    ],
    related: ['intent-vs-geometry', 'vs-xaml', 'what-problem']
  },

  // ── Comparisons (continued) ──────────────────────────────────────────────
  {
    slug: 'vs-xaml',
    category: 'vs',
    navLabel: '.gui vs XAML / QML',
    title: '.gui vs XAML, QML, and GTK .ui: interchange, not a runtime',
    dek: 'The most common reaction to .gui is "isn’t this just XAML?" It has the same markup shape and a different job: those are UI languages bound to a runtime; .gui is a portable target that can emit them.',
    seoTitle: '.gui vs XAML, QML, GTK .ui: what’s different? | .gui Guides',
    seoDescription: 'XAML, QML, and GTK .ui are declarative UI languages tied to their own runtimes. .gui is a portable interchange format one layer above them: it can be converted to XAML, SwiftUI, Compose, or HTML, and isn’t a framework itself.',
    datePublished: '2026-07-29',
    dateModified: '2026-07-29',
    body: [
      { type: 'p', text: 'Show a markup-based UI format to enough engineers and someone will say "so… XAML?", and they’re not wrong to notice the resemblance. XAML, QML, GTK’s <code>.ui</code>, JavaFX FXML, and <code>.gui</code> all describe interfaces as declarative, tag-based markup. The XKCD "now there are 15 competing standards" reflex is the honest thing to feel here. The difference isn’t syntax; it’s <strong>what the file is for</strong>.' },
      { type: 'h2', text: 'XAML/QML/.ui are runtimes; .gui is an interchange target' },
      { type: 'p', text: 'XAML is a UI language for Microsoft’s frameworks (WPF, WinUI, MAUI); QML is Qt’s; GTK <code>.ui</code> is GTK’s; FXML is JavaFX’s. Each is bound to <em>its own</em> runtime and toolchain: a XAML file expects the .NET layout engine, data-binding system, and control library to be present, and it is meaningless without them. That binding is a feature for building an app on that stack and a wall for moving a design off it. <code>.gui</code> deliberately has <strong>no runtime of its own</strong>: it’s not a framework, it runs no logic (<a href="/guides/vs-html">.gui vs HTML</a>), and it isn’t meant to be the application you ship.' },
      { type: 'p', text: 'The mental model is one layer up. Think of <code>.gui</code> as sitting <em>above</em> XAML/SwiftUI/Compose the way SVG sits above a specific rendering engine: a portable, human-readable representation of a UI that can be previewed, edited, versioned, generated by AI, and then <em>converted into</em> any of those runtime languages, rather than competing with them (<a href="/guides/what-problem">What problem does .gui solve?</a>). Asking "XAML or <code>.gui</code>?" is a category error; the intended answer is ".gui, then generate the XAML."' },
      { type: 'h2', text: 'Where the analogy to XAML breaks down' },
      { type: 'table', head: ['', 'XAML / QML / .ui', '.gui'], rows: [
        ['Primary purpose', 'Author an app on one framework', 'Exchange a design between tools, AI, and platforms'],
        ['Runtime', 'Bound to one (.NET, Qt, GTK)', 'None: converted to a target'],
        ['Logic / bindings', 'Yes: code-behind, data binding', 'No logic; static by design'],
        ['Portability across stacks', 'Not a goal', 'The entire goal'],
        ['Meant to ship as-is', 'Yes', 'No: it’s the source, not the product']
      ] },
      { type: 'p', text: '"But MAUI already runs XAML cross-platform" is the strongest version of the objection. It’s true, and it proves the point rather than refuting it: MAUI makes XAML portable <em>across Microsoft’s runtime on multiple OSes</em>. It does not let a Figma plugin, a web CDN viewer, a Swift codebase, and an arbitrary AI agent all read and write the same file without the .NET stack. Cross-platform-within-one-ecosystem is not the same problem as tool-and-model-agnostic interchange, which is the one <code>.gui</code> targets.' },
      { type: 'h2', text: 'Why reuse a markup shape at all, then?' },
      { type: 'p', text: 'Because the resemblance is the point: models are trained on enormous amounts of tag-based markup, so an AI agent writing <code>.gui</code> is closer to writing JSX than to learning a novel schema (<a href="https://github.com/dotgui/core/blob/main/rfcs/0001-xml-over-json.md">RFC-0001</a>). Borrowing the <em>familiar shape</em> of XAML-family markup while dropping the runtime binding is a deliberate trade, not an accident: the goal was the most learnable possible surface for both humans and models, not a new aesthetic.' },
      { type: 'p', text: 'The XKCD worry only really applies to a <em>15th runtime</em>. A portable interchange layer whose whole job is to convert <em>into</em> the existing runtimes is the opposite move: fewer re-authoring steps between the standards that already exist, not one more island beside them.' }
    ],
    faq: [
      { q: 'Isn’t .gui just XAML with different tags?', a: 'They share a declarative, tag-based shape but not a purpose. XAML is a UI language bound to Microsoft’s runtime: it needs the .NET layout and binding engine to mean anything. .gui has no runtime of its own; it’s a portable interchange file that gets converted into XAML, SwiftUI, Compose, or HTML. You wouldn’t pick one over the other; you’d design in .gui and generate the XAML.' },
      { q: 'MAUI already runs XAML cross-platform, doesn’t that cover this?', a: 'It covers cross-platform within Microsoft’s runtime. It doesn’t let a design tool, a web viewer, a Swift codebase, and an arbitrary AI agent all read and write the same file without the .NET stack. .gui targets tool- and model-agnostic interchange, which is a different problem from one framework running on several operating systems.' },
      { q: 'Isn’t this the "15 competing standards" problem?', a: 'That reflex applies to a new runtime competing with existing ones. .gui isn’t a runtime; it’s a layer above them whose job is to convert into XAML, SwiftUI, Compose, and HTML. It aims to reduce re-authoring between existing standards, not to become a 15th framework beside them.' },
      { q: 'Why copy XAML-style markup instead of inventing a cleaner syntax?', a: 'Because familiarity is the feature. AI models are trained on huge amounts of tag-based markup, so writing .gui is close to writing JSX rather than learning a new schema. The format reuses the learnable shape of markup while dropping the runtime binding that ties XAML to .NET.' }
    ],
    related: ['vs-html', 'what-problem', 'intent-vs-geometry']
  },
  {
    slug: 'vs-react-vue',
    category: 'vs',
    navLabel: '.gui vs React / Vue',
    title: '.gui vs React and Vue: a file format, not a UI framework',
    dek: 'A question that comes up fast: "why is the dotgui site built in Vue, not .gui?" Because .gui isn’t a framework you deploy; it’s the design the framework gets built from. Here’s the distinction.',
    seoTitle: '.gui vs React & Vue: is it a framework alternative? | .gui Guides',
    seoDescription: 'React and Vue are UI frameworks you build and ship an app with. .gui is a portable design file format, not a runtime: it doesn’t replace React or Vue, it describes a design you then generate React or Vue code from.',
    datePublished: '2026-07-29',
    dateModified: '2026-07-29',
    body: [
      { type: 'p', text: 'When people first meet <code>.gui</code>, a very common reflex is to slot it next to React or Vue and ask which one wins. There’s even a sharp version of the question aimed straight at this site: <em>"if <code>.gui</code> is so good, why is dotgui.org itself built in Vue instead of <code>.gui</code>?"</em> It’s a fair thing to ask, and the answer is the whole distinction: <strong>React and Vue are UI frameworks you build and run an application with; <code>.gui</code> is a design file format, not a framework at all</strong> (<a href="/guides/not-a-runtime">.gui is not a runtime</a>). They aren’t competing; they sit at different stages of the same pipeline.' },
      { type: 'h2', text: 'Different layers, not different options' },
      { type: 'p', text: 'React and Vue are <strong>runtimes</strong>: you install them, write components that hold state and logic, and ship a running application whose interface only exists after their code executes in a browser. <code>.gui</code> runs no logic and ships nothing; it’s a static, self-contained file that <em>describes</em> an interface (<a href="/guides/vs-html">.gui vs HTML</a>). Asking "React or <code>.gui</code>?" is like asking "React or a Figma file?": the design is the input, the framework is what you build from it. The right sentence is "design it in <code>.gui</code>, then generate the React (or Vue) code," not "pick one."' },
      { type: 'table', head: ['', 'React / Vue', '.gui'], rows: [
        ['What it is', 'A UI framework / runtime', 'A design file format'],
        ['You install it?', 'Yes, plus a toolchain', 'No, you open the file'],
        ['Holds state & logic', 'Yes', 'No: static by design'],
        ['Is the shipped app', 'Yes', 'No: it’s the design the app is built from'],
        ['Portable across stacks', 'No: framework-specific', 'Yes: convert to React, Vue, SwiftUI, Compose, HTML']
      ] },
      { type: 'h2', text: 'So why is this site built in Vue?' },
      { type: 'p', text: 'Because that question actually reveals how the format is meant to be used, not a contradiction. dotgui.org is a real, deployed web application: it needs routing, interactivity, and a runtime, which is exactly the job a framework like Vue exists to do and exactly the job <code>.gui</code> deliberately does <em>not</em> do. What actually happened is the useful part: the site’s pages were <strong>designed as <code>.gui</code> files first</strong> (generated with AI, iterated on, previewed), and once the design was right, converted into a Vue project to ship. The <code>.gui</code> file was the source of truth for the design; Vue is the runtime it was built into. A design format shipping <em>as itself</em> would be the contradiction, the same way you wouldn’t deploy a Figma file as your production frontend.' },
      { type: 'callout', tone: 'do', text: 'The mental model: .gui is upstream of your framework. Ideate and agree on the design as a .gui file, then generate React/Vue/SwiftUI/Compose from it and build the real app there.' },
      { type: 'h2', text: 'Where each one is the right tool' },
      { type: 'p', text: 'Reach for React or Vue when you’re building the actual product: anything with behavior, data, and state that has to run. Reach for <code>.gui</code> one step earlier: to generate and compare interface ideas cheaply, hand a design between an AI agent, a designer, and a developer as one portable file, and keep a readable source of truth for what the screen is supposed to look like before it’s entangled in framework code (<a href="/guides/what-problem">What problem does .gui solve?</a>). One doesn’t replace the other; <code>.gui</code> makes the step <em>before</em> React or Vue an open, machine-readable artifact instead of a screenshot or a locked design-tool document.' }
    ],
    faq: [
      { q: 'Is .gui a replacement for React or Vue?', a: 'No. React and Vue are UI frameworks you install and ship a running app with; they hold state and logic. .gui is a static design file format that runs no logic and ships nothing. It doesn’t compete with them; you design a screen as a .gui file and then generate React or Vue code from it, the way you’d build from a Figma file. They’re different stages of the same pipeline.' },
      { q: 'Why is the dotgui website built in Vue instead of .gui?', a: 'Because dotgui.org is a real deployed web app that needs a runtime (routing, interactivity, state), which is exactly what a framework like Vue is for and exactly what .gui deliberately isn’t. The site’s pages were designed as .gui files first (generated with AI and iterated on), then converted into a Vue project to ship. The .gui file was the design source of truth; Vue is the runtime it was built into. Deploying a design format as-is would be the actual contradiction.' },
      { q: 'Can I build a full application directly from a .gui file?', a: 'Not as a runtime: a .gui file has no logic, state, or data binding, so it isn’t a shippable app on its own. What you do is generate framework code (React, Vue, SwiftUI, Compose, HTML) from it and build the real app there. .gui is the portable design upstream of the framework, not a substitute for it.' }
    ],
    related: ['vs-html', 'not-a-runtime', 'what-problem']
  },

  // ── Best practices (continued) ───────────────────────────────────────────
  {
    slug: 'handoff-and-fidelity',
    category: 'practice',
    navLabel: 'Handoff & fidelity',
    title: 'Handoff, pixel-perfection, and your component library',
    dek: 'The fair developer objection: "a designer sends me a .gui, AI interprets it, it won’t be pixel-perfect, and it won’t map to our internal components." True, and not what .gui is claiming to do.',
    seoTitle: 'Handoff, fidelity, and component libraries in .gui | .gui Guides',
    seoDescription: 'Why .gui isn’t a pixel-perfect codegen promise: it’s an exchange and ideation format. How to use it realistically alongside an internal component library and a real front-end.',
    datePublished: '2026-07-29',
    dateModified: '2026-07-29',
    body: [
      { type: 'p', text: 'One of the most grounded objections raised about the format comes from developers, not designers: <em>a designer hands me a <code>.gui</code>, an AI layer interprets it into code, that output is not going to be pixel-perfect, and it won’t map to our internal component system, so for a real web project, isn’t it useless?</em> The honest answer is that this is a real limitation of <em>one</em> workflow, and it’s not the workflow <code>.gui</code> is actually selling.' },
      { type: 'h2', text: 'What .gui does and doesn’t promise' },
      { type: 'callout', tone: 'dont', text: 'It does NOT promise: feed a .gui file to a code generator and get production code that pixel-matches the design and slots into your existing component library. No format delivers that reliably, because your component library is opinionated in ways a portable file can’t know about.' },
      { type: 'callout', tone: 'do', text: 'It DOES promise: a portable, readable, convertible description of a screen that a designer, an AI agent, and a developer can all open, for ideation, review, and a strong first-draft translation, not a final build.' },
      { type: 'p', text: 'This is the same boundary every portable design format lives inside. A Figma file doesn’t emit your production components either; a developer looks at it and rebuilds the screen with the team’s own primitives. <code>.gui</code> doesn’t change that reality; it makes the thing being handed over an <em>open, diffable, AI-readable file</em> instead of a screenshot or a link to a vendor workspace (<a href="/guides/vs-figma">.gui vs Figma files</a>).' },
      { type: 'h2', text: 'The component-library gap is real, and unavoidable' },
      { type: 'p', text: 'Every serious front-end team has a highly opinionated component library, and generated markup that doesn’t map to it will get looked at and rebuilt by hand regardless of source format. That’s not a <code>.gui</code> failure; it’s true of any design-to-code path, including Figma-to-code. What a semantic format can do is make the rebuild <em>cheaper</em>: because <code>.gui</code> carries <a href="/spec/roles">roles</a> (<code>role="button"</code>, <code>role="card"</code>) and <a href="/spec/tokens">tokens</a> rather than only geometry, an agent mapping a screen onto your <code>&lt;Button&gt;</code> and <code>&lt;Card&gt;</code> has explicit intent to match against, instead of inferring "this rounded box was probably a button" from pixels (<a href="/guides/intent-vs-geometry">Intent vs geometry</a>).' },
      { type: 'h2', text: 'Where it actually pays off' },
      { type: 'p', text: 'The value shows up before the pixel-perfect stage, not at it. A developer can prompt an idea, get a <code>.gui</code> file, and share it with a designer for feedback without touching production Figma or the app itself (<a href="/guides/what-problem">What problem does .gui solve?</a>). A designer can hand a developer a file that previews identically in any browser with one script tag (<a href="/embed">the embed library</a>) and reads as structured intent, so the "what did they mean here" round-trips shrink. The final, pixel-perfect implementation is still a developer building with the team’s components; <code>.gui</code> just makes everything upstream of that step portable and machine-readable.' },
      { type: 'callout', tone: 'do', text: 'Realistic expectation: treat generated code from a .gui file as a first draft and a source of intent, then implement for real with your own component library, exactly as you already do with a Figma handoff.' }
    ],
    faq: [
      { q: 'Will code generated from a .gui file be pixel-perfect?', a: 'No, and it doesn’t claim to be. .gui is an exchange and ideation format, not a codegen guarantee. Generated code is a strong first draft carrying explicit intent (roles, tokens), which a developer then implements properly with their own component library, the same as a Figma-to-code handoff.' },
      { q: 'Our team has its own component library, the output won’t map to it. Is .gui useless for us?', a: 'The generated markup won’t map to your components automatically, but neither does any design format, including Figma. What .gui adds is that the handoff artifact is an open, AI-readable file carrying roles and tokens, so mapping a screen onto your <Button>/<Card> has explicit intent to match instead of guessing from pixels. It makes the rebuild cheaper, not automatic.' },
      { q: 'So how is a .gui handoff better than a Figma handoff?', a: 'It’s portable and machine-readable without a vendor account or API: it previews in any browser with one script tag, version-controls as text, is diffable, and an AI agent can read exactly what’s on screen. The developer still rebuilds with their own components, but everything upstream of that step is an open file rather than a locked workspace.' }
    ],
    related: ['vs-figma', 'what-problem', 'intent-vs-geometry']
  }
]

export const guideSlugs = guideEntries.map(g => g.slug)

export function getGuideEntry(slug: string): GuideEntry | undefined {
  return guideEntries.find(g => g.slug === slug)
}

export const guideGroups = (['concepts', 'vs', 'practice'] as GuideCategory[]).map(category => ({
  category,
  label: guideCategoryLabels[category],
  items: guideEntries.filter(g => g.category === category)
}))
