/**
 * Hand-authored content for /guides and /guides/<slug>.
 *
 * Unlike spec-data.ts (generated from core/), there is no canonical source
 * for this content elsewhere in the monorepo — it lives here. Adding a new
 * guide is one new object appended to `guideEntries`; no new .vue file, no
 * manual route/sitemap/llms edit (all three are derived from this file, see
 * nuxt.config.ts, scripts/gen-sitemap.ts, scripts/gen-llms.ts).
 *
 * `text` fields may contain inline <code>/<strong>/<a> — rendered with
 * v-html in GuideBody.vue, same convention spec pages use for prose.
 */

export type GuideCategory = 'vs' | 'practice'

export type GuideBlock =
  | { type: 'p'; text: string }
  | { type: 'h2'; text: string }
  | { type: 'list'; items: string[] }
  | { type: 'code'; lang: string; code: string; label?: string }
  | { type: 'callout'; tone: 'do' | 'dont'; text: string }
  | { type: 'table'; head: string[]; rows: string[][] }

export interface GuideFaq { q: string; a: string }

export interface GuideEntry {
  slug: string
  category: GuideCategory
  navLabel: string
  title: string
  dek: string
  seoTitle: string
  seoDescription: string
  datePublished: string
  dateModified: string
  body: GuideBlock[]
  faq: GuideFaq[]
  related: string[]
}

export const guideCategoryLabels: Record<GuideCategory, string> = {
  vs: 'Comparisons',
  practice: 'Best practices'
}

export const guideEntries: GuideEntry[] = [
  // ── Comparisons ──────────────────────────────────────────────────────────
  {
    slug: 'vs-css',
    category: 'vs',
    navLabel: '.gui vs CSS',
    title: '.gui vs CSS: a file format vs a styling language',
    dek: 'CSS styles a document that already exists somewhere else. .gui is the document — structure, layout, and appearance in one file, with no cascade to fight.',
    seoTitle: '.gui vs CSS — what’s the difference? | .gui Guides',
    seoDescription: 'CSS is a styling language layered onto HTML’s DOM. .gui is a self-contained file format for the whole interface — no cascade, no specificity, no host document required.',
    datePublished: '2026-07-10',
    dateModified: '2026-07-10',
    body: [
      { type: 'p', text: '<strong>CSS styles something that already exists.</strong> It is a rule language that attaches presentation to a DOM another format (HTML) already built — selectors, specificity, inheritance, a cascade that resolves at render time based on document order and rule weight. <strong>.gui is the thing itself.</strong> A <code>.gui</code> file is a zip package — <code>design.guix</code> markup, an <code>assets/</code> folder, a <code>preview.webp</code> thumbnail — that fully describes one interface: structure, layout, and appearance, together, in one file. There is no separate document to style and no cascade to resolve, because there is nothing upstream of it.' },
      { type: 'h2', text: 'What that actually changes' },
      { type: 'p', text: 'In CSS, the same element can end up styled by five different rules from three different files, and the final appearance depends on specificity math and load order. Reading a stylesheet does not tell you what anything looks like — you have to run the cascade in your head. In <code>.gui</code>, every node carries its own resolved appearance attributes directly, plus optional <a href="/spec/tokens">design tokens</a> (<code>$brand</code>, <code>$spacing-md</code>) for values meant to repeat. There is one place a value lives and one place it’s read from.' },
      { type: 'p', text: 'Layout works the same way. CSS spacing between siblings is usually simulated — margins on the parent or child, sometimes an empty spacer element left over from table-layout habits. <code>.gui</code>’s <a href="/spec/row"><code>row</code></a>, <a href="/spec/col"><code>col</code></a>, and <a href="/spec/grid"><code>grid</code></a> elements take a literal <code>gap</code> attribute — one declared number, no simulated elements. See <a href="/guides/spacing-and-gaps">Spacing and gaps</a>.' },
      { type: 'h2', text: 'Direction and alignment as values, not axis algebra' },
      { type: 'p', text: 'CSS expresses "these children run horizontally, evenly spaced" as a style declaration repeated on every container — <code>display: flex; flex-direction: row; gap: 16px</code> — whether it’s hand-written or generated by a utility system like Tailwind’s class list. <code>.gui</code> expresses the same thing as one element: <code>&lt;row gap="16"&gt;</code>. Direction is the tag itself, not a property that has to be set correctly and can silently be left off.' },
      { type: 'p', text: 'Alignment follows the same pattern. CSS splits it into two axis-relative properties — <code>justify-content</code> for the main axis, <code>align-items</code> for the cross axis — and which axis is "main" flips depending on <code>flex-direction</code>, a piece of mental bookkeeping baked into the model. <code>.gui</code> replaced both with a single <code>align</code> attribute using nine positional values (<code>top-left</code> … <code>bottom-right</code>) that always name a visual position directly, the way a designer already describes layout, rather than a main-axis/cross-axis calculation — modeled on Figma’s own alignment grid, not flexbox terminology.' },
      { type: 'p', text: 'There’s no controlled benchmark for the token difference this makes, but the intent is explicit in the format’s own design record: a single <code>row</code> or one <code>align="middle-center"</code> value is harder for a model to get wrong than a multi-property, axis-relative CSS block, and there’s less text to generate for the same layout intent either way.' },
      { type: 'h2', text: 'Why this matters for AI agents' },
      { type: 'p', text: 'An agent asked to "style this the way the mockup looks" using CSS has to reason about cascade order across every stylesheet that could touch the element. An agent asked to change a <code>.gui</code> node’s fill changes one attribute on one node — nothing else in the file is implicated. That’s also what makes <code>.gui</code> deterministically <a href="/spec/quality">scoreable</a>: a validator can check a CSS ruleset for syntax errors, but it can’t tell you the cascade produced a sane result. A <code>.gui</code> file’s resolved appearance is just sitting there, readable, checkable.' },
      { type: 'p', text: '<strong>.gui</strong> is not trying to replace CSS on the web — a browser still needs CSS to paint DOM. What <code>.gui</code> replaces is using CSS (or a CSS-in-JS system, or Tailwind classes) as the source of truth for a design. The design lives in the <code>.gui</code> file; CSS, if it appears at all, is one possible render target for it, generated rather than hand-maintained.' }
    ],
    faq: [
      { q: 'Does .gui replace CSS?', a: 'No — a browser still uses CSS to paint. .gui replaces CSS (or any styling system) as the source of truth for a design: the design lives in the .gui file, and any styling code is a generated render target, not the original.' },
      { q: 'Why doesn’t .gui have a cascade?', a: 'Because every node carries its own resolved appearance directly, plus optional token references for values meant to repeat. There’s no upstream document to cascade from, so there’s nothing to resolve — what you read on a node is what renders.' },
      { q: 'How does .gui handle repeated values without a cascade?', a: 'Design tokens ($brand, $spacing-md, etc.) — a node references a token by name instead of repeating a literal value. That gets you reuse without needing cascade or inheritance rules to find out which value actually applies.' }
    ],
    related: ['vs-html', 'spacing-and-gaps', 'ccac-score']
  },
  {
    slug: 'vs-html',
    category: 'vs',
    navLabel: '.gui vs HTML',
    title: '.gui vs HTML: a closed vocabulary vs an open runtime',
    dek: 'HTML is a programming surface that happens to describe UI. .gui is a static, closed vocabulary that always terminates in the same picture, everywhere.',
    seoTitle: '.gui vs HTML — how are they different? | .gui Guides',
    seoDescription: 'HTML plus CSS and JS is an open, scriptable runtime. .gui is a closed, static vocabulary of layout and shape elements with no logic — which is what makes it diffable and scoreable.',
    datePublished: '2026-07-10',
    dateModified: '2026-07-10',
    body: [
      { type: 'p', text: 'HTML, in practice, is never just HTML — it’s HTML plus CSS plus JavaScript, an open runtime where arbitrary code can mutate the DOM at any time. Two loads of the same page can render differently depending on network timing, a feature flag, or a script that hasn’t finished executing yet. <strong>.gui has no scripting.</strong> It is a closed, fixed vocabulary — <code>row</code>, <code>col</code>, <code>frame</code>, <code>grid</code>, <code>text</code>, <code>img</code>, <code>rect</code>, <code>ellipse</code>, <code>line</code> — and nothing in that vocabulary can execute logic. A given <code>.gui</code> file renders to the same picture every time, on every renderer, because there is no code path for it to do otherwise.' },
      { type: 'h2', text: 'What "closed vocabulary" buys you' },
      { type: 'p', text: 'A file that can’t run code is a file that can be fully understood by reading it. That’s what makes a <code>.gui</code> file <strong>diffable</strong> (two versions differ by exactly the attributes that changed, not by whatever a script does at runtime), <strong>validatable</strong> (a fixed vocabulary has a fixed set of legal shapes to check against), and <strong>scoreable</strong> (see <a href="/spec/quality">the CCAC model</a>) — none of which is meaningfully possible for an arbitrary HTML+JS bundle, because the actual rendered result depends on execution, not just the source.' },
      { type: 'h2', text: 'Where HTML still wins' },
      { type: 'p', text: 'HTML is the right choice when the interface needs behavior — a live feed, client-side validation, a WebSocket connection. <code>.gui</code> is not a competitor there; it’s a source-of-truth format for the design that a real app (in HTML, SwiftUI, Jetpack Compose, whatever) then gets built from. The <a href="/embed"><code>&lt;gui-embed&gt;</code></a> library renders a <code>.gui</code> file directly on a web page with one script tag when you do want it live in a browser, but the file itself stays inert — no logic, no side effects, same output every render.' },
      { type: 'p', text: 'The role vocabulary closes the same gap semantic HTML tries to close with tags like <code>&lt;nav&gt;</code> or <code>&lt;article&gt;</code> — except <code>.gui</code>’s <a href="/spec/roles">53 roles</a> are a closed, enumerated set rather than a loose convention, so <code>role="button"</code> means the same thing in every file, not "probably a button, check the click handler to be sure."' },
      { type: 'h2', text: 'Borrowing the idea, not the tax' },
      { type: 'p', text: 'HTML started as a simple trio — markup, style, script. In practice almost nobody hand-writes plain HTML for a real interface today; the actual authoring surface is a JavaScript framework (React, Vue, and the rest) sitting on top, and that layer is where most of the weight now lives. HTML won by adoption, not because raw markup is a great design representation — it’s the one format every browser, tool, and person already knows, so "design in code" defaults to it by network effect more than by merit.' },
      { type: 'p', text: '<code>.gui</code> borrows HTML’s actual insight — plain markup any tool can parse, no proprietary format underneath — while trying not to inherit what widespread adoption did to it. A small, concrete example lives in its own layout vocabulary: the underlying primitive is a single <a href="/spec/stack"><code>&lt;stack direction="..."&gt;</code></a> element, but writing <code>direction="horizontal"</code> on every row-shaped container turned out to be noisy in practice, so <code>&lt;row&gt;</code>, <code>&lt;col&gt;</code>, and <code>&lt;grid&gt;</code> exist as sugar that drop the <code>direction</code> attribute for the common case. Same capability, less to write, less for an agent to get wrong — cutting tax on an idea, not just copying it.' }
    ],
    faq: [
      { q: 'Can a .gui file contain JavaScript or run logic?', a: 'No. The element vocabulary is closed and static — there is no scripting surface. A .gui file always renders to the same output because there is no code path for it to differ.' },
      { q: 'Is .gui meant to replace HTML for building apps?', a: 'No. HTML (or SwiftUI, Compose, etc.) is still the right choice for interfaces with real behavior. .gui is a source-of-truth design format those apps get built from, not a runtime.' },
      { q: 'How does .gui handle semantic meaning without HTML tags like <nav> or <button>?', a: 'A closed 53-role vocabulary via the role= attribute — role="button", role="nav-bar", and so on. Unlike semantic HTML, every role means exactly one thing everywhere, since the vocabulary is fixed rather than a loose convention.' },
      { q: 'Is row/col/grid a different format from stack, or the same thing?', a: 'The same thing. row, col, and grid are sugar tags for stack with a direction already set — row is stack direction="horizontal", col is stack direction="vertical". stack remains valid to write directly; the sugar tags just remove the extra attribute for the common case.' }
    ],
    related: ['vs-css', 'vs-svg', 'common-agent-mistakes']
  },
  {
    slug: 'vs-figma',
    category: 'vs',
    navLabel: '.gui vs Figma',
    title: '.gui vs Figma files: portable text vs a vendor’s app',
    dek: 'A Figma file only exists inside Figma. A .gui file is plain text in a zip — readable, diffable, and versionable without opening any design tool.',
    seoTitle: '.gui vs a Figma file — what changes? | .gui Guides',
    seoDescription: 'A Figma file lives inside Figma’s app and servers. A .gui file is a portable zip of plain-text XML — no vendor lock, git-diffable, and authorable without a design tool at all.',
    datePublished: '2026-07-10',
    dateModified: '2026-07-10',
    body: [
      { type: 'p', text: 'A Figma file is only fully readable inside Figma — the app, the API, or an export. It’s an excellent design environment, but the file itself is not a portable artifact you can open in a text editor, diff in git, or hand to an agent without going through Figma’s servers. <strong>A <code>.gui</code> file is plain text.</strong> Unzip it and <code>design.guix</code> is readable XML — open it in any editor, <code>git diff</code> it line by line, generate it from a script with no design tool involved at all.' },
      { type: 'h2', text: '.gui doesn’t require Figma' },
      { type: 'p', text: 'The <a href="/figma">Figma plugin</a> exports any Figma layer tree to a <code>.gui</code> file — auto-layout, fills, gradients, effects, and tokens carried over as a 1:1 mapping of Figma’s own layer model, not approximated. That makes Figma <strong>one entry point among several</strong>, not a requirement. An agent can write a <code>.gui</code> file directly from a prompt with no design tool touched at any point — see <a href="/guides/prompting-your-agent">Prompting your agent</a>.' },
      { type: 'h2', text: 'The loop, not a one-way export' },
      { type: 'p', text: 'Because the same file is legible to both a design tool and an agent, it can move in either direction: an agent writes <code>home.gui</code>, a designer opens it in Figma to nudge a color, the file goes back to the agent to wire up. Every stop in that loop reads and writes the same file — nothing gets re-derived from a screenshot at each step. That loop is the actual point; Figma export is one leg of it, not the whole story.' },
      { type: 'h2', text: 'No live connection required' },
      { type: 'p', text: 'Figma’s own AI integration path runs through MCP (Model Context Protocol) — a live tool-calling connection where an agent queries Figma’s API, often across several round-trips, to reconstruct a design piece by piece. Exporting to <code>.gui</code> once removes that dependency: the result is a static file an agent reads directly, with no persistent connection, no repeated API calls, and no dependency on Figma’s servers being reachable at generation time.' }
    ],
    faq: [
      { q: 'Do I need Figma to create a .gui file?', a: 'No. An AI agent with the dotgui skill installed (via gui setup) can write a .gui file directly from a prompt — Figma is one entry point among several, not a requirement.' },
      { q: 'What gets preserved when exporting a Figma design to .gui?', a: 'Auto-layout, fills, gradients, effects, and design tokens — a 1:1 mapping of Figma’s own layer model, not an approximation.' },
      { q: 'Can I open a .gui file back in Figma after an agent edits it?', a: 'That’s the point of the format: the same file is legible to a design tool and an agent, so it can move in either direction instead of only exporting once.' },
      { q: 'Does reading a .gui file require an MCP connection to Figma?', a: 'No. Once a design is exported to .gui, it’s a static file — no live connection, API calls, or access to Figma’s servers required to read it.' }
    ],
    related: ['vs-screenshots', 'vs-css', 'prompting-your-agent']
  },
  {
    slug: 'vs-screenshots',
    category: 'vs',
    navLabel: '.gui vs a screenshot',
    title: '.gui vs a screenshot or PNG mockup',
    dek: 'A picture is a dead end — an agent has to guess spacing, hierarchy, and color from pixels. A .gui file hands those values over directly, already structured.',
    seoTitle: '.gui vs a screenshot mockup — why a file, not pixels | .gui Guides',
    seoDescription: 'A PNG mockup has no structure — an agent regenerating from it has to guess layout, spacing, and color from pixels. A .gui file preserves those values as literal, editable data.',
    datePublished: '2026-07-10',
    dateModified: '2026-07-10',
    body: [
      { type: 'p', text: 'A mockup is a picture. However it was made — Figma export, a hand-drawn comp, a screenshot of a competitor’s app — once it’s a PNG, the structure that produced it is gone. An agent asked to build from it has to reverse-engineer spacing, hierarchy, and exact colors from pixels: is that gap 16px or 20px? Is that gray <code>#F5F5F5</code> or <code>#F4F4F4</code>? Nothing in a screenshot answers that with certainty.' },
      { type: 'h2', text: 'Structure survives, instead of being reverse-engineered' },
      { type: 'p', text: 'A <code>.gui</code> file keeps the values that produced the picture, not just the picture. A <code>gap="16"</code> attribute is unambiguous in a way that a rendered 16px visual gap in a PNG is not. A <code>fill="$surface"</code> token reference tells you a color is intentional and reused, something a screenshot can’t distinguish from a one-off. Editing a <code>.gui</code> file means changing one attribute; editing a mockup to explore a variant usually means regenerating the whole image and hoping the rest stayed consistent.' },
      { type: 'h2', text: 'It still renders to a picture — that part didn’t go away' },
      { type: 'p', text: 'A <code>.gui</code> file always renders to a real preview image too (<code>preview.webp</code>, part of every package) — nothing is lost by moving to structured data. The difference is the picture is a byproduct of the file, not the only artifact that exists. An agent, a designer, and a renderer can all work from the same source instead of each starting over from pixels.' },
      { type: 'h2', text: 'Still true as vision models improve' },
      { type: 'p', text: 'A more capable vision model closes some of this gap, but it doesn’t remove the extraction step — reading a screenshot still means inferring structure, spacing, and hierarchy from pixels, a lossy process that can guess wrong with just as much confidence as it guesses right. A <code>.gui</code> file skips extraction entirely: the structure is already data, not something to be reconstructed.' },
      { type: 'p', text: 'That’s what makes <code>.gui</code> work as a design handoff format specifically: export once, and any AI tool downstream reads the actual design, with nothing to reverse-engineer and nothing to hallucinate — the difference between receiving a file and receiving a description of one.' }
    ],
    faq: [
      { q: 'Does a .gui file still have a visual preview like a screenshot?', a: 'Yes — every .gui package includes a preview.webp thumbnail. The difference is that the structured markup that produced it is preserved alongside it, not thrown away.' },
      { q: 'Why can’t an AI agent just work from a screenshot directly?', a: 'It can, but it has to guess exact spacing, hierarchy, and colors from pixels — there’s no way to tell an intentional 16px gap from an accidental 15px one in a raster image. A .gui file states the value directly.' },
      { q: 'Do better vision models make this comparison less relevant?', a: 'Not really — a stronger model still has to run an extraction step to infer structure from pixels, and extraction can produce a confident wrong answer. A .gui file has nothing to extract; the structure is already the data.' }
    ],
    related: ['vs-figma', 'spacing-and-gaps', 'vs-css']
  },
  {
    slug: 'vs-svg',
    category: 'vs',
    navLabel: '.gui vs SVG',
    title: '.gui vs SVG: graphics format vs interface format',
    dek: 'SVG made graphics text. .gui borrows that idea but is purpose-built for interface layout and semantics — things SVG was never designed to express.',
    seoTitle: '.gui vs SVG — same idea, different job | .gui Guides',
    seoDescription: 'SVG describes shapes and paths as readable text but has no layout system or semantic vocabulary for UI. .gui applies SVG’s idea specifically to interfaces: layout, roles, and tokens included.',
    datePublished: '2026-07-10',
    dateModified: '2026-07-10',
    body: [
      { type: 'p', text: 'SVG proved something important: a graphic doesn’t have to be a raster of pixels. It can be readable text — <code>&lt;circle&gt;</code>, <code>&lt;path&gt;</code>, <code>&lt;rect&gt;</code> — that any tool can parse, diff, and edit directly. <code>.gui</code> takes that same premise and applies it to interfaces instead of arbitrary graphics: the way <code>.svg</code> is to graphics, <code>.gui</code> is to UI.' },
      { type: 'h2', text: 'Why SVG alone doesn’t cover interfaces' },
      { type: 'p', text: 'SVG has no concept of a layout system — no flex-like <code>row</code>/<code>col</code> with a <code>gap</code>, no responsive behavior, no design tokens, no idea of what a "button" or "nav bar" is. Everything in an SVG is either an absolutely positioned shape or a manually computed path. That’s exactly right for an icon or an illustration, and exactly wrong for a screen that needs to lay itself out, carry semantic roles, and reference reusable tokens.' },
      { type: 'p', text: '<code>.gui</code> adds the layer SVG is missing: <a href="/spec/row"><code>row</code></a>/<a href="/spec/col"><code>col</code></a>/<a href="/spec/grid"><code>grid</code></a> for layout with a real <code>gap</code>, <a href="/spec/tokens">design tokens</a> for values meant to repeat, and a closed <a href="/spec/roles">53-role vocabulary</a> so a node can declare <em>what it is</em> (<code>role="button"</code>), not just how it’s drawn. Shape primitives (<code>rect</code>, <code>ellipse</code>, <code>line</code>) exist in <code>.gui</code> too, so an icon or illustration can sit inside a <code>.gui</code> file natively — it just isn’t the whole story the way it is in SVG.' },
      { type: 'h2', text: 'Why .gui is a package, not a single file' },
      { type: 'p', text: 'There’s a second gap SVG leaves for interfaces: a single SVG file has nowhere good to put a real photo. Embedding an actual raster image means either linking an external URL — the file alone no longer carries what it needs, so portability breaks — or inlining it as base64 text, which bloats the file enormously. If an AI model has to pass that file through, it pays the token cost of every base64 character even though the image data is completely opaque to it.' },
      { type: 'p', text: 'That cost is measured, not assumed: in early testing, inlining just two to four images as base64 consumed roughly half the token budget of a multi-hour session converting a file. Plain path references cost nothing to reference.' },
      { type: 'p', text: 'That’s one of the two reasons <code>.gui</code> is defined as a zip package rather than a flat text file: real image files sit in an <code>assets/</code> folder alongside the markup, referenced by a plain relative path (<code>src="assets/hero.webp"</code>). See <a href="/guides/vs-screenshots">.gui vs a screenshot</a> for why keeping the structure itself — not just the image — is the bigger point.' }
    ],
    faq: [
      { q: 'Can I put SVG shapes inside a .gui file?', a: '.gui has its own shape primitives — rect, ellipse, line — that cover the same ground for icons and simple graphics inside a screen, alongside the layout and role vocabulary SVG doesn’t have.' },
      { q: 'Why not just extend SVG with a layout system instead of a new format?', a: 'SVG’s design targets arbitrary vector graphics, not application interfaces — it has no concept of roles, tokens, or a UI-shaped element vocabulary. .gui borrows SVG’s "readable text, not pixels" idea but is purpose-built for UI from the ground up.' },
      { q: 'Why is .gui a zip package instead of a single text file like SVG?', a: 'Mainly to keep real images as real files instead of inlined base64 text. Testing found that inlining a handful of images as base64 could consume roughly half the token budget of a long AI session — a plain path reference into the package’s assets/ folder costs almost nothing by comparison.' }
    ],
    related: ['vs-html', 'vs-css', 'layout-row-col-grid']
  },

  // ── Best practices ───────────────────────────────────────────────────────
  {
    slug: 'prompting-your-agent',
    category: 'practice',
    navLabel: 'Prompting your agent',
    title: 'Prompting your AI agent to build a .gui file',
    dek: 'gui setup teaches your own agent the format. Here’s the mental model and what to actually say.',
    seoTitle: 'How to prompt an AI agent to build a UI in .gui | .gui Guides',
    seoDescription: 'How to get Claude Code, Cursor, or Gemini CLI to design a UI as a .gui file: install the skill with gui setup, the agent → skill → gui mental model, and what to say.',
    datePublished: '2026-07-10',
    dateModified: '2026-07-10',
    body: [
      { type: 'p', text: '<strong>.gui contains no AI.</strong> The CLI and the reference engine are 100% deterministic — validation, rendering, and scoring, zero model calls. The actual design generation happens in <strong>your own agent</strong> — Claude Code, Gemini CLI, Cursor, Codex, whatever you already use. <code>gui setup</code> installs the dotgui skill into that agent, so when you ask it to build something, it already knows the format instead of guessing at markup.' },
      { type: 'h2', text: 'The mental model' },
      { type: 'code', lang: 'text', label: 'The loop', code: 'you ──ask──▶ your agent ──uses──▶ dotgui skill ──calls──▶ gui (this tool)' },
      { type: 'p', text: 'You ask in plain language. The skill tells your agent the format’s vocabulary, conventions, and pitfalls (see <a href="/guides/common-agent-mistakes">Common agent mistakes</a>). The agent writes <code>design.guix</code> markup directly, then calls the <code>gui</code> CLI to validate and package it — <code>gui</code> never designs anything itself, it only checks and packages what the agent wrote.' },
      { type: 'h2', text: 'Getting started' },
      { type: 'code', lang: 'bash', label: 'One-time setup', code: 'npm i -g @dotgui/cli\ngui setup   # installs the dotgui skill into detected agents' },
      { type: 'p', text: '<code>gui setup</code> asks for one confirmation and installs into each detected agent’s skill directory (e.g. <code>~/.claude/skills/dotgui/</code>). After that, a plain-language ask is enough.' },
      { type: 'h2', text: 'What to actually say' },
      { type: 'callout', tone: 'do', text: 'Say what the screen is for and let the agent choose structure: "a stocks watchlist screen, dark mode, one card per holding." The skill already knows the vocabulary — you don’t need to write markup yourself.' },
      { type: 'callout', tone: 'dont', text: 'Don’t ask for "a screenshot" or "a mockup image" of the UI — that sends the agent toward pixels instead of a .gui file, and you lose everything covered in vs a screenshot or PNG mockup.' },
      { type: 'callout', tone: 'do', text: 'If you already have a reference — a competitor’s screen, a Figma file, a hand sketch — hand it over and ask for a .gui file built from it. The skill handles translating intent into the format’s elements, roles, and tokens.' },
      { type: 'p', text: 'Once you have a file, iteration is just more asks: "make the balance number larger," "use the brand token for the CTA fill." Each change is a targeted edit to the existing file, not a regeneration from scratch.' }
    ],
    faq: [
      { q: 'Does gui setup work with any AI coding agent?', a: 'It installs the dotgui skill into detected agents — Claude Code, Gemini CLI, Cursor, Codex, and others with a skill/plugin model. For agents without one, it prints the format snippet to add manually.' },
      { q: 'Does the gui CLI itself generate designs?', a: 'No — the CLI and engine are 100% deterministic, zero AI. Your own agent does the designing; gui only reads, validates, lints, renders, and packages the result.' },
      { q: 'What should I say to my agent to get a .gui file instead of a mockup image?', a: 'Just ask for what the screen is for in plain language — after gui setup, the skill already tells the agent to produce a .gui file. Avoid asking for a "screenshot" or "image," which points the agent at pixels instead of structured markup.' }
    ],
    related: ['common-agent-mistakes', 'spacing-and-gaps', 'vs-screenshots']
  },
  {
    slug: 'common-agent-mistakes',
    category: 'practice',
    navLabel: 'Common agent mistakes',
    title: 'Common mistakes AI agents make in .gui files',
    dek: 'An agent that hasn’t been taught the format brings habits over from HTML and CSS that don’t belong in .gui. Here are the five that show up most.',
    seoTitle: 'Common AI agent mistakes in .gui files | .gui Guides',
    seoDescription: 'The habits AI agents carry over from HTML/CSS that don’t belong in .gui: fake spacer rows instead of gap, hardcoded colors instead of tokens, missing role=, and more.',
    datePublished: '2026-07-10',
    dateModified: '2026-07-10',
    body: [
      { type: 'p', text: 'An agent that generates <code>.gui</code> without the dotgui skill installed (see <a href="/guides/prompting-your-agent">Prompting your agent</a>) will often fall back on HTML/CSS habits that technically validate but miss what the format is actually for. These are the five that show up most.' },
      { type: 'h2', text: '1. Faking spacing with an empty row' },
      { type: 'callout', tone: 'dont', text: 'Adding an empty <col height="16"/> between two elements to create visual space — a leftover habit from table-based HTML layout.' },
      { type: 'callout', tone: 'do', text: 'Use the gap attribute on the parent row or col. One declared number, no dead markup. Full explanation in Spacing and gaps.' },
      { type: 'h2', text: '2. Hardcoding colors instead of using tokens' },
      { type: 'p', text: 'Repeating the same literal <code>fill="#2B6BE4"</code> across a dozen nodes instead of declaring it once as a <a href="/spec/tokens">token</a> and referencing <code>$brand</code>. This directly costs points on the <strong>Consistent</strong> level of <a href="/spec/quality">CCAC scoring</a> — a file that hand-repeats a value doesn’t agree with itself the way a token-backed one does.' },
      { type: 'h2', text: '3. Skipping role= entirely' },
      { type: 'p', text: 'Leaving structural nodes without a <a href="/spec/roles"><code>role=</code></a> anchor. It costs nothing to add and it’s the entire basis of the <strong>Comprehensible</strong> CCAC level — a button without <code>role="button"</code> is invisible to any tool trying to read the file’s semantics, not just to a human.' },
      { type: 'h2', text: '4. Over-nesting containers' },
      { type: 'p', text: 'Wrapping a <code>row</code> inside a <code>col</code> inside a <code>frame</code> when a single <code>row</code> would do — an old defensive-div habit. Extra nesting with no layout purpose is exactly what the <strong>Clean</strong> CCAC level flags as waste.' },
      { type: 'h2', text: '5. Forgetting the assets folder' },
      { type: 'p', text: 'Referencing an <code>img</code> <code>src</code> that doesn’t point to a real file inside the package’s <code>assets/</code> folder. A file can be syntactically valid and still be broken this way — the <strong>Intact</strong> gate (part of CCAC’s scoring gate) exists specifically to catch it.' }
    ],
    faq: [
      { q: 'Why do AI agents fake spacing with empty elements in .gui?', a: 'It’s a carried-over habit from HTML/CSS, where an invisible spacer element is a common (if outdated) way to force a gap. .gui’s row and col elements take a literal gap attribute instead, so the workaround is unnecessary.' },
      { q: 'Does a hardcoded color still produce a valid .gui file?', a: 'Yes — it validates fine. But it costs points on the Consistent CCAC level, since the file doesn’t agree with itself the way a token-backed value does, and it makes global color changes harder to make correctly.' },
      { q: 'What happens if role= is left off a node?', a: 'The file still validates and renders — role is optional structurally. But it’s the entire basis of the Comprehensible CCAC level, so leaving it off means the node is invisible to any tool or agent trying to read the file’s semantics.' }
    ],
    related: ['spacing-and-gaps', 'ccac-score', 'prompting-your-agent']
  },
  {
    slug: 'spacing-and-gaps',
    category: 'practice',
    navLabel: 'Spacing and gaps',
    title: 'Spacing in .gui: use gap, not an empty row',
    dek: 'The single most common habit agents bring over from HTML/CSS — and the one-attribute fix.',
    seoTitle: 'Spacing in .gui files: gap vs empty spacer rows | .gui Guides',
    seoDescription: 'Why AI agents fake spacing in .gui with empty spacer rows, why it’s wrong, and how the gap attribute on row/col/stack replaces it with one declared value.',
    datePublished: '2026-07-10',
    dateModified: '2026-07-10',
    body: [
      { type: 'p', text: 'A pattern shows up constantly in AI-generated <code>.gui</code> files: an empty element sitting between two real ones, existing only to create visual space.' },
      { type: 'code', lang: 'xml', label: 'Don’t', code: '<col>\n  <text>Balance</text>\n  <col height="16"/>   <!-- fake spacer -->\n  <text>$4,204.10</text>\n</col>' },
      { type: 'p', text: 'It renders correctly, and it will pass a naive visual check against a reference design. It is still wrong, for two concrete reasons: it’s dead markup with no semantic purpose (a node that exists purely as a workaround), and it’s brittle — change the parent’s padding or add a third child and the spacing math has to be redone by hand at every spacer.' },
      { type: 'h2', text: 'The fix: gap' },
      { type: 'p', text: '<a href="/spec/row"><code>row</code></a>, <a href="/spec/col"><code>col</code></a>, and <a href="/spec/grid"><code>grid</code></a> all take a <code>gap</code> attribute — the space between every child, declared once on the parent.' },
      { type: 'code', lang: 'xml', label: 'Do', code: '<col gap="16">\n  <text>Balance</text>\n  <text>$4,204.10</text>\n</col>' },
      { type: 'p', text: 'One number, on the container that actually owns the spacing decision. Add a third child and the gap still applies correctly with no extra markup. This isn’t a style preference — it’s the difference between a value the file can be reasoned about and a value that has to be reverse-engineered from node heights.' },
      { type: 'h2', text: 'Why agents default to the old pattern' },
      { type: 'p', text: 'It’s inherited from HTML, where a real <code>gap</code> property only reliably exists in flex/grid layout contexts and plenty of training data still comes from table-layout-era markup or naive absolute positioning, where an invisible spacer was the only tool available. <code>.gui</code>’s layout elements always support <code>gap</code> — there’s never a context where the workaround is actually necessary, so an agent that reaches for it either hasn’t been told the format has <code>gap</code>, or is pattern-matching from HTML habit. <code>gui setup</code> installs a skill that teaches this explicitly (see <a href="/guides/prompting-your-agent">Prompting your agent</a>).' },
      { type: 'h2', text: 'It also affects your score' },
      { type: 'p', text: 'A dead spacer node is exactly what the <strong>Clean</strong> level of <a href="/spec/quality">CCAC scoring</a> flags — unused markup with no layout purpose. Swapping it for <code>gap</code> is a direct, mechanical fix, not a matter of taste.' }
    ],
    faq: [
      { q: 'Which elements support the gap attribute?', a: 'row, col, and grid — every .gui layout container that arranges children in a direction or track system takes a literal gap attribute for the space between them.' },
      { q: 'Is an empty spacer element ever necessary in .gui?', a: 'No. row, col, and grid always support gap, so there’s no layout situation in .gui that requires a dead spacer node the way older HTML table-layout patterns sometimes did.' },
      { q: 'Does a fake spacer row break validation?', a: 'No, it still validates and renders correctly — which is exactly why it’s easy to miss. It does cost points on the Clean level of CCAC scoring as unused markup.' }
    ],
    related: ['common-agent-mistakes', 'vs-css', 'ccac-score']
  },
  {
    slug: 'ccac-score',
    category: 'practice',
    navLabel: 'Improving your CCAC score',
    title: 'How to get a good CCAC score',
    dek: 'The four levels explained on /spec/quality, turned into concrete things to actually go fix.',
    seoTitle: 'How to improve a .gui file’s CCAC score | .gui Guides',
    seoDescription: 'Practical fixes for each CCAC level — Clean, Consistent, Accessible, Comprehensible — so a .gui file scores well: remove dead markup, use tokens, fix contrast, declare roles.',
    datePublished: '2026-07-10',
    dateModified: '2026-07-10',
    body: [
      { type: 'p', text: 'The <a href="/spec/quality">CCAC model</a> explains what the score measures. This is the companion piece: what to actually change in a file to move each number, assuming a file has already cleared the <strong>Valid + Intact</strong> gate (a file that fails either isn’t scored at all).' },
      { type: 'h2', text: 'Clean — remove waste' },
      { type: 'list', items: ['Delete nodes with no layout or visual purpose — the classic case is an empty spacer element; see Spacing and gaps.', 'Flatten unnecessary nesting: a row wrapped in a col wrapped in a frame, where one container would do.', 'Remove declared tokens or styles that nothing in the file actually references.'] },
      { type: 'h2', text: 'Consistent — agree with yourself' },
      { type: 'list', items: ['Replace repeated literal values (a color, a spacing number used five times) with a single declared token, referenced everywhere.', 'Pick one system and stay in it — don’t mix ad hoc pixel values with token references for the same kind of value across the file.'] },
      { type: 'h2', text: 'Accessible — stay legible' },
      { type: 'list', items: ['Check text-to-background contrast against WCAG 2.2 visual criteria, particularly on colored fills and overlays.', 'Keep tap targets (buttons, interactive rows) at a real minimum size — a role="button" that’s visually tiny still fails this even though it validates.', 'Don’t drop text size below what the criteria allow for body copy.'] },
      { type: 'h2', text: 'Comprehensible — be readable by a machine' },
      { type: 'list', items: ['Add role= to every structural node it applies to, from the closed 53-role vocabulary — a button without role="button" scores as if it isn’t one.', 'Prefer the most specific correct role over a generic one when the vocabulary has it.', 'Remember this level is saturating count, not full coverage — declaring roles on the nodes that matter (nav, actions, key content) moves the number; it doesn’t require tagging literally everything.'] },
      { type: 'p', text: 'None of this is a gate — <a href="/spec/quality">a low score is still a valid, packable file</a>. The score is a diagnostic, not a blocker; treat a low number as a punch list, not a rejection.' }
    ],
    faq: [
      { q: 'Do I need a perfect CCAC score to ship a .gui file?', a: 'No. A low score still describes a valid, packable file — the score is advisory, not a gate. Any pass/fail threshold is a decision made by whatever tool consumes the score, not by the format itself.' },
      { q: 'What’s the fastest single fix to improve a low score?', a: 'Usually adding role= to structural nodes (Comprehensible) or swapping repeated literal values for tokens (Consistent) — both are mechanical changes, not redesigns, and both move the number directly.' },
      { q: 'Does Comprehensible require tagging every single node with a role?', a: 'No — it’s a saturating count on the nodes that matter (nav, actions, key content), not full coverage of every node in the tree.' }
    ],
    related: ['common-agent-mistakes', 'spacing-and-gaps', 'avoiding-generic-ui']
  },
  {
    slug: 'layout-row-col-grid',
    category: 'practice',
    navLabel: 'row vs col vs grid',
    title: 'Structuring a screen: row vs col vs grid',
    dek: 'Three layout elements cover almost every screen. Here’s how to pick between them without guessing.',
    seoTitle: 'row vs col vs grid in .gui — which to use | .gui Guides',
    seoDescription: 'A decision guide for .gui’s layout elements: row for horizontal arrangement, col for vertical, grid for fixed multi-track layouts like card galleries — with examples.',
    datePublished: '2026-07-10',
    dateModified: '2026-07-10',
    body: [
      { type: 'p', text: 'Most screens are built from three layout elements. Picking the right one is mostly about which direction the content actually flows in — not a stylistic choice.' },
      { type: 'h2', text: 'row and col — direction' },
      { type: 'p', text: '<a href="/spec/row"><code>row</code></a> arranges children left to right; <a href="/spec/col"><code>col</code></a> arranges children top to bottom. Both belong to the same underlying stack family and both take <code>gap</code> and standard spacing/alignment attributes (see <a href="/guides/spacing-and-gaps">Spacing and gaps</a>). Default to whichever matches the actual reading direction of the content — a settings list is a <code>col</code> of rows; a button toolbar is a <code>row</code>.' },
      { type: 'code', lang: 'xml', label: 'A settings screen: col of rows', code: '<col gap="12">\n  <row gap="8" role="list-item">\n    <text>Notifications</text>\n  </row>\n  <row gap="8" role="list-item">\n    <text>Privacy</text>\n  </row>\n</col>' },
      { type: 'h2', text: 'grid — fixed multi-track layout' },
      { type: 'p', text: 'Reach for <a href="/spec/grid"><code>grid</code></a> when content repeats across more than one axis at once — a photo gallery, a dashboard of cards, anything that would otherwise be a <code>row</code> of <code>col</code>s (or vice versa) faked to look like a grid. <code>grid</code> takes its own track and <code>gap</code> attributes and expresses the two-axis relationship directly instead of nesting stacks to fake it.' },
      { type: 'code', lang: 'xml', label: 'A card gallery: grid, not nested rows', code: '<grid columns="3" gap="16">\n  <rect role="card"/>\n  <rect role="card"/>\n  <rect role="card"/>\n</grid>' },
      { type: 'h2', text: 'A quick rule of thumb' },
      { type: 'table', head: ['Content shape', 'Use'], rows: [
        ['One direction, one axis (a list, a toolbar)', '<code>row</code> or <code>col</code>'],
        ['Repeats across rows and columns at once', '<code>grid</code>'],
        ['A fixed positioned container or canvas root', '<code>frame</code>']
      ] },
      { type: 'p', text: 'Nesting a <code>row</code> inside a <code>col</code> to fake a grid is exactly the kind of over-nesting the <strong>Clean</strong> CCAC level penalizes (see <a href="/guides/common-agent-mistakes">Common agent mistakes</a>) — if the content is genuinely two-axis, <code>grid</code> is the correct element, not a workaround.' }
    ],
    faq: [
      { q: 'When should I use grid instead of nesting row and col?', a: 'When content repeats across two axes at once — a card gallery, a dashboard — grid expresses that directly. Nesting row inside col to fake the same layout is unnecessary and gets flagged as over-nesting by the Clean CCAC level.' },
      { q: 'What’s the difference between row/col and the stack family mentioned in the spec?', a: 'row and col are the two directional members of the same underlying stack family — row lays out left to right, col lays out top to bottom. Both share the same spacing and alignment attributes.' }
    ],
    related: ['spacing-and-gaps', 'common-agent-mistakes', 'vs-svg']
  },
  {
    slug: 'avoiding-generic-ui',
    category: 'practice',
    navLabel: 'Avoiding generic AI UI',
    title: 'Making AI-generated UI not look generic',
    dek: 'The tells of an unedited AI-generated screen, and the structural (not aesthetic) fixes .gui makes available.',
    seoTitle: 'Avoiding generic-looking AI-generated UI in .gui | .gui Guides',
    seoDescription: 'The recognizable tells of unedited AI-generated interfaces — default gradients, uniform spacing, generic type — and the structural .gui fixes: real tokens, a deliberate type scale, and roles.',
    datePublished: '2026-07-10',
    dateModified: '2026-07-10',
    body: [
      { type: 'p', text: 'Unedited AI-generated interfaces tend to converge on the same handful of tells: a purple-to-blue gradient with no relationship to the product, fully rounded pill buttons everywhere regardless of size, one spacing value (usually 16px) reused for every gap with no rhythm, and a single generic type scale with no real hierarchy. None of this is a <code>.gui</code> problem specifically — it’s what happens when a model defaults instead of deciding. But <code>.gui</code>’s structure makes the fix mechanical rather than vague.' },
      { type: 'h2', text: 'Replace default fills with a real token palette' },
      { type: 'p', text: 'A generic gradient is usually a placeholder nobody committed to. Define <a href="/spec/tokens">tokens</a> that came from the actual product — a brand color, a real neutral scale — and reference them everywhere instead of leaving default fills in place. This is the same fix that improves <strong>Consistent</strong> scoring in <a href="/guides/ccac-score">CCAC</a>: one committed system beats several undecided ones.' },
      { type: 'h2', text: 'Give spacing a scale, not one number' },
      { type: 'p', text: 'Uniform 16px everywhere is a tell precisely because real interfaces don’t space everything identically — related items sit closer together than unrelated sections. Use a small set of deliberate <code>gap</code> values (say 4 / 8 / 16 / 32) and apply the smaller ones inside a group and the larger ones between groups, instead of one value applied everywhere by default.' },
      { type: 'h2', text: 'Use role= to make hierarchy structural, not just visual' },
      { type: 'p', text: 'Generic UI often has visual hierarchy (a bigger font here, a bolder weight there) with nothing underneath it. Declaring <a href="/spec/roles"><code>role=</code></a> on headings, primary actions, and key content makes the hierarchy a structural fact of the file, not just a font-size choice — and it’s the same signal that improves <strong>Comprehensible</strong> scoring.' },
      { type: 'p', text: 'None of this requires design taste to execute — it requires actually deciding on a token set and a spacing scale instead of accepting whatever a model defaulted to, and the closed vocabulary makes it possible to check that those decisions were actually applied consistently across the file.' }
    ],
    faq: [
      { q: 'Why does AI-generated UI often look the same regardless of tool?', a: 'It converges on defaults instead of decisions — the same gradient, the same uniform spacing value, the same generic type scale — because nobody committed to a real token set or spacing scale for the specific product.' },
      { q: 'Can .gui’s quality score catch a generic-looking design?', a: 'CCAC scores the file, not the design’s taste — it won’t flag "boring" directly. But undecided defaults usually show up as inconsistency (repeated literal values instead of a token system), which the Consistent level does catch.' }
    ],
    related: ['ccac-score', 'vs-css', 'common-agent-mistakes']
  }
]

export const guideSlugs = guideEntries.map(g => g.slug)

export function getGuideEntry(slug: string): GuideEntry | undefined {
  return guideEntries.find(g => g.slug === slug)
}

export const guideGroups = (['vs', 'practice'] as GuideCategory[]).map(category => ({
  category,
  label: guideCategoryLabels[category],
  items: guideEntries.filter(g => g.category === category)
}))
